// Trilhas do perfil infantil: linguagem simples, histórias curtas e muita brincadeira.
import {
  concept,
  fill,
  match,
  multi,
  order,
  quiz,
  reflect,
  say,
  scenario,
  slider,
  sort,
  tf,
  type Draft,
} from "./trail-content-levels";
import type { Activity, Level, LevelNumber, Stop, Trail } from "./trail-types";

const level = (stopId: string, n: LevelNumber, drafts: Draft[]): Level => ({
  id: `${stopId}-l${n}`,
  level: n,
  activities: drafts.map((d, i) => ({ ...d, id: `${stopId}-l${n}-${i + 1}` }) as Activity),
});

const stop = (
  id: string,
  title: string,
  icon: string,
  summary: string,
  l1: Draft[],
  l2: Draft[],
  l3: Draft[],
): Stop => ({
  id,
  title,
  icon,
  summary,
  levels: [level(id, 1, l1), level(id, 2, l2), level(id, 3, l3)],
});

/* ─────────────────────────── Trilha 1 · Aventura dos Sabores ─────────────────────────── */

const RAINBOW = stop(
  "kid-1-1",
  "Arco-íris no Prato",
  "🌈",
  "Cada cor de fruta e legume tem um superpoder!",
  [
    concept(
      "cadu",
      "Cada cor tem um superpoder!",
      "Frutas e legumes têm cores lindas, e cada cor ajuda o corpo de um jeito. **Quanto mais cores no prato, mais superpoderes!**",
      [
        "🥕 Laranja: ajuda os olhos",
        "🥦 Verde: deixa o corpo forte",
        "🍅 Vermelho: cuida do coração",
        "🍇 Roxo: ajuda o cérebro",
      ],
      "Tente comer 3 cores diferentes em cada refeição!",
      "🌈",
    ),
    say(
      "cadu",
      "Oi! Eu sou o Cadu Cenoura! Sabia que a minha cor laranja faz bem para os seus olhos?",
    ),
    quiz(
      "cadu",
      "Qual destes alimentos é ALARANJADO?",
      ["Cenoura", "Brócolis", "Uva", "Couve-flor"],
      0,
      "Isso! A cenoura é laranja e ajuda a gente a enxergar bem.",
    ),
    tf(
      "mila",
      "Um prato com várias cores é mais nutritivo.",
      true,
      "Isso mesmo! Cada cor traz nutrientes diferentes.",
    ),
    quiz(
      "tito",
      "De que cor é o brócolis?",
      ["Verde", "Azul", "Rosa", "Preto"],
      0,
      "Verdinho! Os alimentos verdes ajudam o corpo a ficar forte.",
    ),
    match(
      "nina",
      "Ligue o alimento à cor dele:",
      [
        ["Morango", "Vermelho"],
        ["Banana", "Amarelo"],
        ["Alface", "Verde"],
        ["Uva", "Roxo"],
      ],
      "Muito bem! Cada fruta tem a sua cor.",
    ),
    multi(
      "cadu",
      "Quais destes alimentos são VERDES?",
      ["Brócolis", "Couve", "Morango", "Alface"],
      [0, 1, 3],
      "Brócolis, couve e alface são verdinhos! Morango é vermelho.",
    ),
    match(
      "nina",
      "Ligue a fruta ou legume à cor dele:",
      [
        ["Cenoura", "Laranja"],
        ["Uva", "Roxo"],
        ["Tomate", "Vermelho"],
      ],
      "Você já é craque em combinar cores e alimentos!",
    ),
    scenario(
      "cadu",
      "Na hora do lanche, Cadu quer ficar com os olhos fortes para enxergar bem de longe.",
      "Qual alimento vai ajudar mais?",
      ["Cenoura", "Bala", "Refrigerante", "Biscoito"],
      0,
      "A cenoura é laranja e cheia de vitamina A, que ajuda os olhos a enxergarem bem!",
    ),
    reflect("mila", "Qual é a sua fruta ou legume colorido favorito? Por quê?"),
  ],
  [
    concept(
      "nina",
      "Montando um prato colorido",
      "Para um prato de campeão, escolha **uma cor de cada tipo**: algo verde, algo laranja ou amarelo, algo vermelho e uma proteína, como feijão ou ovo.",
      [
        "Verde: folhas e brócolis",
        "Laranja ou amarelo: cenoura e abóbora",
        "Vermelho: tomate e beterraba",
      ],
      "Prato bonito é prato gostoso!",
      "🍽️",
    ),
    sort(
      "cadu",
      "Coloque cada alimento na cor certa:",
      ["Verde", "Vermelho", "Laranja"],
      [
        ["Couve", 0],
        ["Alface", 0],
        ["Tomate", 1],
        ["Morango", 1],
        ["Cenoura", 2],
        ["Laranja", 2],
      ],
      "Boa! Você separou tudo direitinho.",
    ),
    multi(
      "mila",
      "Quais destes alimentos são vermelhos?",
      ["Tomate", "Morango", "Banana", "Cereja", "Alface"],
      [0, 1, 3],
      "Tomate, morango e cereja são vermelhos. Banana é amarela e alface é verde!",
    ),
    tf(
      "lipe",
      "Comer só alimentos de uma cor é a melhor escolha.",
      false,
      "É melhor misturar! Cada cor traz algo diferente para o corpo.",
    ),
    fill(
      "nina",
      "Um prato bem ___ é um prato cheio de superpoderes!",
      ["colorido", "vazio", "sem graça", "escuro"],
      0,
      "Colorido! Quanto mais cores, melhor.",
    ),
    order(
      "cadu",
      "Monte o prato colorido na ordem:",
      [
        "Coloque as folhas verdes",
        "Adicione algo laranja",
        "Adicione o feijão",
        "Finalize com um tomate vermelho",
      ],
      "Assim o prato fica lindo e completo!",
    ),
    match(
      "tito",
      "Ligue o alimento à cor que ainda falta no prato:",
      [
        ["Milho", "Amarelo"],
        ["Berinjela", "Roxo"],
        ["Pimentão vermelho", "Vermelho"],
      ],
      "Cada cor a mais deixa o prato mais completo!",
    ),
    scenario(
      "mila",
      "Mila está montando o prato dela: já colocou arroz e frango.",
      "O que ela pode adicionar para deixar o prato mais colorido?",
      ["Uma salada de tomate e alface", "Mais arroz", "Só frango", "Nada, está pronto"],
      0,
      "Uma salada colorida completa o prato com vitaminas e cores novas!",
    ),
    slider(
      "cadu",
      "Quantas cores diferentes de alimentos de verdade é legal ter no prato?",
      { min: 1, max: 5, step: 1, unit: " cores" },
      3,
      1,
      "Um bom objetivo é ter pelo menos 3 cores diferentes em cada refeição!",
    ),
  ],
  [
    concept(
      "lipe",
      "Cores escondidas",
      "Nem tudo que faz bem é colorido por fora! Couve-flor, cebola e alho são claros, mas têm **muitos nutrientes**. E as cores das frutas são naturais, diferentes das cores de bala, que vêm de corantes.",
      [
        "Branco também vale: couve-flor, cebola, alho",
        "Cor de fruta é natural",
        "Cor de bala vem de corante",
      ],
      "Cor de fruta é natural. Cor de bala é corante!",
      "🕵️",
    ),
    quiz(
      "mila",
      "De onde vem a cor da beterraba?",
      ["Da própria beterraba, é natural", "De tinta", "De corante de bala", "De açúcar"],
      0,
      "A cor da beterraba nasce com ela. É totalmente natural!",
    ),
    tf(
      "cadu",
      "As balas coloridas têm a mesma cor natural das frutas.",
      false,
      "As balas usam corantes. Só as frutas têm cor natural.",
    ),
    multi(
      "tito",
      "Quais alimentos têm cor natural?",
      ["Cenoura", "Uva", "Bala de goma", "Beterraba", "Refresco em pó"],
      [0, 1, 3],
      "Cenoura, uva e beterraba têm cor natural. Bala e refresco em pó usam corantes.",
    ),
    sort(
      "nina",
      "Alimento de verdade ou de pacote?",
      ["De verdade", "De pacote"],
      [
        ["Morango", 0],
        ["Cenoura", 0],
        ["Uva", 0],
        ["Bala de goma", 1],
        ["Refresco em pó", 1],
        ["Salgadinho", 1],
      ],
      "Frutas e legumes são alimentos de verdade, direto da natureza.",
    ),
    match(
      "cadu",
      "Ligue a cor ao superpoder:",
      [
        ["Laranja", "Ajuda os olhos"],
        ["Verde", "Deixa o corpo forte"],
        ["Vermelho", "Cuida do coração"],
        ["Roxo", "Ajuda o cérebro"],
      ],
      "Agora você já sabe o que cada cor faz!",
    ),
    multi(
      "nina",
      "Quais destes NÃO precisam de corante, porque a cor já é natural?",
      ["Beterraba", "Bala de goma", "Cenoura", "Refresco em pó"],
      [0, 2],
      "Beterraba e cenoura já nascem com essas cores lindas!",
    ),
    fill(
      "cadu",
      "A cor da fruta é ___, mas a cor da bala vem de corante.",
      ["natural", "de tinta", "de lápis", "mágica"],
      0,
      "Natural! As frutas já nascem com a cor delas.",
    ),
    order(
      "lipe",
      "Coloque em ordem para descobrir se um alimento tem cor natural:",
      [
        "Pense se ele é uma fruta ou legume de verdade",
        "Veja se ele nasceu assim, da terra ou da árvore",
        "Se sim, a cor dele é natural",
        "Se for um doce bem colorido, a cor é corante",
      ],
      "Ótimo! Agora você é um detetive de cores.",
    ),
    reflect(
      "tito",
      "Existe algum alimento colorido que você nunca provou? Que tal experimentar um dia desses?",
    ),
  ],
);

const FRUITS = stop(
  "kid-1-2",
  "Frutas e Legumes",
  "🍓",
  "Descubra frutas, legumes e verduras, e como comer mais delas.",
  [
    concept(
      "mila",
      "Frutas, legumes e verduras são amigos",
      "**Frutas** costumam ser docinhas e nascem em árvores ou plantas. **Legumes** e **verduras** combinam com o almoço e o jantar. Todos têm vitaminas para você crescer forte!",
      [
        "Frutas: maçã, banana, laranja",
        "Legumes: cenoura, abóbora, chuchu",
        "Verduras: alface, couve, espinafre",
      ],
      "Uma boa meta é comer frutas e vegetais todos os dias!",
      "🍎",
    ),
    quiz(
      "mila",
      "Qual destas é uma FRUTA?",
      ["Maçã", "Alface", "Batata", "Couve"],
      0,
      "A maçã é uma fruta gostosa e cheia de fibras.",
    ),
    tf(
      "tito",
      "Verduras como alface e couve ajudam o corpo a ficar forte.",
      true,
      "Isso! Elas têm vitaminas e minerais importantes.",
    ),
    match(
      "lipe",
      "Ligue o grupo ao exemplo:",
      [
        ["Fruta", "Banana"],
        ["Verdura", "Alface"],
        ["Legume", "Cenoura"],
      ],
      "Muito bem! Você já sabe separar os grupos.",
    ),
    quiz(
      "cadu",
      "Qual fruta tem casca amarela e é macia por dentro?",
      ["Banana", "Melancia", "Uva", "Morango"],
      0,
      "A banana! Ótima para o lanche.",
    ),
    fill(
      "nina",
      "Frutas, verduras e legumes têm muitas ___ para o corpo crescer forte.",
      ["vitaminas", "balas", "tintas", "pedrinhas"],
      0,
      "Vitaminas! Elas ajudam o corpo a funcionar bem.",
    ),
    match(
      "mila",
      "Ligue a fruta ao grupo dela:",
      [
        ["Morango", "Fruta"],
        ["Espinafre", "Verdura"],
        ["Chuchu", "Legume"],
      ],
      "Você já reconhece cada grupo direitinho!",
    ),
    multi(
      "cadu",
      "Quais destas são FRUTAS?",
      ["Manga", "Cenoura", "Uva", "Abobrinha"],
      [0, 2],
      "Manga e uva são frutas! Cenoura e abobrinha são legumes.",
    ),
    scenario(
      "lipe",
      "No lanche da escola, Léo só quer comer biscoito.",
      "Qual seria uma boa troca, mantendo o lanche gostoso?",
      ["Uma fruta picada", "Mais biscoito", "Refrigerante", "Nada"],
      0,
      "Uma fruta picada é doce, gostosa e cheia de vitaminas!",
    ),
    reflect("nina", "Qual fruta ou legume novo você toparia experimentar essa semana?"),
  ],
  [
    concept(
      "nina",
      "Como comer mais frutas e legumes",
      "Dá para colocar frutas e legumes em **todas as refeições**: fruta no café da manhã e no lanche, legumes no almoço e no jantar. Provar coisas novas ajuda a gostar.",
      [
        "Prove uma colherzinha de cada coisa nova",
        "Experimente de jeitos diferentes: cru, cozido, assado",
        "Escolha junto com a família no mercado",
      ],
      "Às vezes precisamos provar 10 vezes até gostar. Continue tentando!",
      "🛒",
    ),
    sort(
      "mila",
      "Fruta, legume ou verdura?",
      ["Fruta", "Legume", "Verdura"],
      [
        ["Maçã", 0],
        ["Banana", 0],
        ["Cenoura", 1],
        ["Abóbora", 1],
        ["Alface", 2],
        ["Couve", 2],
      ],
      "Isso! Cada um tem o seu grupo.",
    ),
    tf(
      "tito",
      "Se você não gostou de um alimento na primeira vez, nunca vai gostar.",
      false,
      "Nosso paladar aprende! Provar de novo ajuda a gostar.",
    ),
    multi(
      "cadu",
      "Quais são boas ideias de lanche?",
      [
        "Fruta picada",
        "Iogurte com fruta",
        "Bala",
        "Salgadinho",
        "Cenoura com pasta de grão-de-bico",
      ],
      [0, 1, 4],
      "Fruta, iogurte e cenoura são lanches fortes e gostosos.",
    ),
    order(
      "mila",
      "Como lavar uma fruta antes de comer?",
      [
        "Lave as mãos",
        "Lave a fruta em água corrente",
        "Esfregue a casca com cuidado",
        "Seque e coma",
      ],
      "Lavar as mãos e a fruta protege a barriguinha.",
    ),
    quiz(
      "lipe",
      "Qual é uma boa hora para comer frutas?",
      ["No lanche e na sobremesa", "Só no aniversário", "Nunca", "Só quando está doente"],
      0,
      "Frutas são ótimas todos os dias!",
    ),
    match(
      "tito",
      "Ligue o alimento ao jeito de prepará-lo:",
      [
        ["Cenoura", "Crua ou cozida"],
        ["Banana", "Descascar e comer"],
        ["Abóbora", "Cozida ou assada"],
      ],
      "Cada legume pode ser preparado de vários jeitos gostosos!",
    ),
    scenario(
      "tito",
      "Dudu provou brócolis pela primeira vez e não gostou muito.",
      "O que ele pode fazer?",
      [
        "Provar de novo outro dia, de outro jeito",
        "Nunca mais comer legumes",
        "Desistir de vegetais para sempre",
        "Comer só doces",
      ],
      0,
      "Nosso paladar muda! Provar de novo, de um jeito diferente, ajuda a descobrir se a gente gosta.",
    ),
    slider(
      "mila",
      "Às vezes precisamos provar um alimento novo várias vezes até começar a gostar dele. Quantas vezes, mais ou menos?",
      { min: 1, max: 15, step: 1, unit: " vezes" },
      10,
      5,
      "Estudos mostram que o paladar pode levar cerca de 10 tentativas para se acostumar com um sabor novo!",
    ),
    tf(
      "cadu",
      "Comer frutas e legumes de jeitos diferentes, como cru, cozido ou assado, pode ajudar a gostar mais deles.",
      true,
      "Isso mesmo! Cada jeito de preparo muda o gosto e a textura.",
    ),
  ],
  [
    concept(
      "tito",
      "Fruta inteira é melhor",
      "Uma fruta inteira tem **fibras**, que ajudam a barriga a funcionar e deixam a gente satisfeito. O suco de caixinha tem muito açúcar adicionado e poucas fibras.",
      [
        "Fruta inteira é melhor que suco",
        "Suco de caixinha tem açúcar adicionado",
        "A água é a melhor bebida",
      ],
      "Fruta de sobremesa é um docinho natural!",
      "🍊",
    ),
    quiz(
      "tito",
      "O que é melhor para o lanche?",
      ["Uma laranja inteira", "Suco de caixinha", "Refrigerante", "Bala"],
      0,
      "A laranja inteira tem fibras e vitaminas.",
    ),
    tf(
      "mila",
      "O suco de caixinha tem tantas fibras quanto a fruta inteira.",
      false,
      "Ele tem poucas fibras e, muitas vezes, açúcar adicionado.",
    ),
    multi(
      "cadu",
      "O que a fibra da fruta faz?",
      [
        "Ajuda a barriga a funcionar",
        "Deixa a gente satisfeito",
        "Estraga os dentes",
        "Deixa o corpo mais forte por dentro",
      ],
      [0, 1],
      "As fibras ajudam a barriga e a saciedade.",
    ),
    sort(
      "nina",
      "Melhor escolha ou só de vez em quando?",
      ["Melhor escolha", "Só de vez em quando"],
      [
        ["Maçã", 0],
        ["Banana", 0],
        ["Uva", 0],
        ["Suco de caixinha", 1],
        ["Gelatina de pacote", 1],
        ["Bala de fruta", 1],
      ],
      "As frutas de verdade são a melhor escolha!",
    ),
    fill(
      "mila",
      "A ___ da fruta ajuda o intestino a funcionar bem.",
      ["fibra", "tinta", "bala", "cola"],
      0,
      "A fibra ajuda a barriguinha.",
    ),
    match(
      "lipe",
      "Ligue a fruta ao jeito de comer:",
      [
        ["Laranja", "Chupar os gomos"],
        ["Banana", "Descascar e comer"],
        ["Melancia", "Comer em fatias"],
        ["Uva", "Lavar e comer no cacho"],
      ],
      "Cada fruta tem o seu jeito gostoso de comer!",
    ),
    quiz(
      "tito",
      "O que tem MAIS fibras?",
      ["Laranja inteira", "Suco de laranja coado", "Refrigerante de laranja"],
      0,
      "A laranja inteira guarda todas as fibras. O suco coado perde boa parte delas.",
    ),
    scenario(
      "mila",
      "Bia tomou um suco de caixinha no lanche e, pouco depois, já estava com fome de novo.",
      "O que poderia ter ajudado mais a segurar a fome?",
      ["Comer a fruta inteira", "Tomar mais suco", "Comer um doce", "Nada, já estava bom"],
      0,
      "A fruta inteira tem fibras que dão mais saciedade do que o suco.",
    ),
    reflect("cadu", "Você prefere comer a fruta inteira ou tomar em suco? Por quê?"),
  ],
);

const WATER = stop(
  "kid-1-3",
  "Água, a Super Bebida",
  "💧",
  "Por que a água é tão importante e como beber mais.",
  [
    concept(
      "nina",
      "Água é vida!",
      "Nosso corpo precisa de **muita água** para funcionar: ela ajuda a digestão, a pele e a manter o corpo na temperatura certa. Quando sentimos sede, o corpo está pedindo água!",
      [
        "Beba água durante o dia todo",
        "Leve uma garrafinha para a escola",
        "Brincou muito? Beba mais água!",
      ],
      "Um corpo bem hidratado tem mais energia para brincar!",
      "💧",
    ),
    quiz(
      "nina",
      "Qual é a melhor bebida para matar a sede?",
      ["Água", "Refrigerante", "Suco de caixinha", "Achocolatado"],
      0,
      "A água é a melhor amiga da sede.",
    ),
    tf(
      "tito",
      "Depois de brincar bastante, o corpo precisa de mais água.",
      true,
      "Isso! A gente perde água suando quando se movimenta.",
    ),
    quiz(
      "cadu",
      "Quando devemos beber água?",
      ["Durante o dia todo", "Só de manhã", "Só no verão", "Só quando estiver doente"],
      0,
      "A água faz bem em qualquer hora do dia.",
    ),
    fill(
      "lipe",
      "Quando sentimos ___, é sinal de que o corpo quer água.",
      ["sede", "sono", "frio", "riso"],
      0,
      "A sede é o aviso do corpo.",
    ),
    tf(
      "mila",
      "Refrigerante mata a sede tão bem quanto a água.",
      false,
      "Refrigerante tem muito açúcar. A água é sempre a melhor.",
    ),
    multi(
      "nina",
      "Quais são boas horas para beber água?",
      ["De manhã", "Depois de brincar", "Só se estiver doente", "Durante o dia todo"],
      [0, 1, 3],
      "Água faz bem em qualquer hora, e ainda mais depois de brincar bastante!",
    ),
    scenario(
      "cadu",
      "Enzo está com a boca seca e sedento no recreio.",
      "O que ele deve fazer?",
      ["Beber água", "Esperar até chegar em casa", "Comer bala", "Nada"],
      0,
      "Sentir sede é o corpo pedindo água. O melhor é beber logo!",
    ),
    slider(
      "nina",
      "Quantos copos de água você acha legal beber ao longo de um dia na escola?",
      { min: 1, max: 8, step: 1, unit: " copos" },
      4,
      2,
      "Beber água várias vezes ao longo do dia, mesmo em pequenas quantidades, ajuda muito!",
    ),
    reflect("lipe", "Você já bebeu água hoje? Que tal beber um copo agora mesmo?"),
  ],
  [
    concept(
      "mila",
      "Água em todo lugar",
      "A água não está só no copo: ela também está em **melancia, laranja e pepino**. E ela é ótima para os dentes. Refrigerantes e sucos adoçados podem causar cáries.",
      [
        "Melancia e laranja têm muita água",
        "A água faz bem aos dentes",
        "Bebidas doces aumentam o risco de cárie",
      ],
      "Dica: água com fatias de fruta fica bem gostosa!",
      "🍉",
    ),
    sort(
      "mila",
      "Bebida para todo dia ou só de vez em quando?",
      ["Todo dia", "Só de vez em quando"],
      [
        ["Água", 0],
        ["Água de coco", 0],
        ["Água com limão sem açúcar", 0],
        ["Refrigerante", 1],
        ["Suco de caixinha", 1],
        ["Achocolatado", 1],
      ],
      "A água é a bebida do dia a dia. As bebidas doces ficam para ocasiões especiais.",
    ),
    multi(
      "nina",
      "Quais alimentos têm muita água?",
      ["Melancia", "Pepino", "Biscoito", "Laranja", "Torrada"],
      [0, 1, 3],
      "Frutas e legumes ajudam a nos hidratar.",
    ),
    order(
      "cadu",
      "Ordene o dia da água:",
      [
        "Beba um copo ao acordar",
        "Leve a garrafinha para a escola",
        "Beba depois de brincar",
        "Beba um copo antes de dormir",
      ],
      "Assim você bebe água durante o dia todo.",
    ),
    tf("lipe", "Bebidas doces fazem bem para os dentes.", false, "O açúcar ajuda a formar cáries."),
    quiz(
      "tito",
      "O que é melhor para acompanhar o almoço?",
      ["Água", "Refrigerante", "Refresco em pó", "Bala"],
      0,
      "Água é a melhor companheira das refeições.",
    ),
    match(
      "mila",
      "Ligue a fruta à quantidade de água que ela tem:",
      [
        ["Melancia", "Muita água"],
        ["Pepino", "Muita água"],
        ["Banana", "Um pouco menos de água"],
      ],
      "Frutas com muita água ajudam bastante na hidratação!",
    ),
    scenario(
      "nina",
      "No time de futebol, depois do treino, todo mundo está suado e com sede.",
      "O que é melhor para repor a água do corpo?",
      ["Água", "Refrigerante gelado", "Achocolatado", "Suco bem doce"],
      0,
      "Depois de suar bastante, a água é sempre a melhor escolha para repor o que foi perdido.",
    ),
    tf(
      "cadu",
      "Comer melancia também ajuda a se hidratar.",
      true,
      "A melancia é quase toda feita de água, além de ser doce e gostosa!",
    ),
    reflect("tito", "Qual fruta com bastante água você mais gosta de comer no verão?"),
  ],
  [
    concept(
      "lipe",
      "Como saber se bebi água suficiente?",
      "Uma dica é olhar a cor do xixi: **clarinha** é sinal de boa hidratação; **escura** é sinal de que é hora de beber mais água.",
      ["Clarinho: tudo certo", "Escuro: beba mais água", "Boca seca e muita sede: peça água"],
      "É importante ficar de olho no seu corpo!",
      "🔎",
    ),
    quiz(
      "mila",
      "Se o xixi está bem escuro, o que fazer?",
      ["Beber mais água", "Comer bala", "Tomar refrigerante", "Não fazer nada"],
      0,
      "Beber água ajuda o corpo a se hidratar.",
    ),
    tf(
      "nina",
      "Todas as pessoas precisam exatamente da mesma quantidade de água.",
      false,
      "Depende da idade, do calor e das brincadeiras.",
    ),
    multi(
      "tito",
      "Quando precisamos beber MAIS água?",
      [
        "No calor",
        "Depois de correr",
        "Quando está frio e quietinho",
        "Quando está doente com febre",
      ],
      [0, 1, 3],
      "Calor, exercício e febre pedem mais água.",
    ),
    match(
      "cadu",
      "Ligue a situação ao que fazer:",
      [
        ["Estou com sede", "Beber água"],
        ["Brinquei muito", "Beber água e descansar"],
        ["Vou para a escola", "Levar a garrafinha"],
      ],
      "Você já sabe cuidar da sua hidratação!",
    ),
    sort(
      "nina",
      "Preciso beber água?",
      ["Preciso de água", "Estou bem hidratado"],
      [
        ["Sede", 0],
        ["Boca seca", 0],
        ["Xixi escuro", 0],
        ["Xixi clarinho", 1],
        ["Sem sede", 1],
        ["Boca úmida", 1],
      ],
      "Fique de olho nos sinais do corpo.",
    ),
    fill(
      "lipe",
      "A água ajuda o corpo a ter muita ___ para brincar.",
      ["energia", "preguiça", "tinta", "sujeira"],
      0,
      "Energia! Água é combustível para brincar.",
    ),
    multi(
      "nina",
      "Quais sinais mostram que o corpo está bem hidratado?",
      ["Xixi clarinho", "Sem sede", "Boca úmida", "Xixi bem escuro"],
      [0, 1, 2],
      "Xixi clarinho, sem sede e boca úmida são sinais de que está tudo certo!",
    ),
    scenario(
      "mila",
      "Depois de um dia bem quente brincando lá fora, Sofia sente a boca seca e um pouco de dor de cabeça.",
      "O que ela deveria fazer primeiro?",
      [
        "Beber água e descansar na sombra",
        "Continuar correndo no sol",
        "Comer um salgadinho",
        "Nada, vai passar sozinho",
      ],
      0,
      "Boca seca e dor de cabeça no calor podem ser sinal de desidratação. Água e sombra ajudam muito!",
    ),
    reflect("tito", "O que te ajuda a lembrar de beber água ao longo do dia?"),
  ],
);

/* ─────────────────────────── Trilha 2 · Corpo Forte e Feliz ─────────────────────────── */

const BREAKFAST = stop(
  "kid-2-1",
  "Café da Manhã de Campeão",
  "🥣",
  "Comece o dia com energia e aprenda a montar lanches fortes.",
  [
    concept(
      "tito",
      "O primeiro combustível do dia",
      "Durante a noite, o corpo passa muitas horas sem comer. O **café da manhã** dá energia para estudar, brincar e prestar atenção.",
      [
        "Fruta, pão integral, ovo ou iogurte",
        "Leite ou água para beber",
        "Coma algo antes de sair de casa",
      ],
      "Um café da manhã bom ajuda na escola!",
      "🥣",
    ),
    quiz(
      "tito",
      "Qual é um café da manhã forte e gostoso?",
      ["Pão integral com ovo e fruta", "Só refrigerante", "Só bala", "Nada"],
      0,
      "Energia, proteína e fruta: um café de campeão!",
    ),
    tf(
      "mila",
      "Pular o café da manhã ajuda a ter mais energia.",
      false,
      "Sem café da manhã, o corpo fica sem combustível.",
    ),
    match(
      "cadu",
      "Ligue o alimento ao que ele dá:",
      [
        ["Fruta", "Vitaminas"],
        ["Ovo", "Proteína"],
        ["Pão integral", "Energia"],
        ["Leite", "Cálcio para os ossos"],
      ],
      "Cada alimento tem sua missão!",
    ),
    fill(
      "nina",
      "O café da manhã é a primeira ___ do dia.",
      ["refeição", "brincadeira", "aula", "soneca"],
      0,
      "Refeição! É a hora de recarregar.",
    ),
    quiz(
      "lipe",
      "Qual bebida combina com o café da manhã?",
      ["Leite ou água", "Refrigerante", "Guaraná", "Suco em pó"],
      0,
      "Leite e água são ótimas companhias.",
    ),
    multi(
      "tito",
      "O que combina num café da manhã de campeão?",
      ["Fruta", "Ovo", "Bala", "Pão integral"],
      [0, 1, 3],
      "Fruta, ovo e pão integral dão energia de verdade para o dia.",
    ),
    scenario(
      "nina",
      "Théo acordou atrasado e quer sair de casa sem comer nada.",
      "O que seria melhor para ele fazer?",
      [
        "Comer algo rápido, como uma fruta com pão",
        "Sair sem comer nada",
        "Comer só bala no caminho",
        "Tomar refrigerante",
      ],
      0,
      "Mesmo rápido, um lanchinho com fruta e pão dá energia para o dia começar bem.",
    ),
    order(
      "cadu",
      "Coloque em ordem uma manhã de campeão:",
      [
        "Acordar e lavar o rosto",
        "Tomar um café da manhã completo",
        "Escovar os dentes",
        "Ir para a escola com energia",
      ],
      "Assim o dia começa com tudo!",
    ),
    reflect("lipe", "O que você mais gosta de comer no café da manhã?"),
  ],
  [
    concept(
      "nina",
      "Montando um café da manhã",
      "Escolha **energia + proteína + fruta**: assim você fica com energia por mais tempo.",
      [
        "Energia: pão integral, aveia, tapioca",
        "Proteína: ovo, queijo, iogurte",
        "Fruta: banana, mamão, laranja",
      ],
      "Cereais muito doces dão energia rápida, mas passam depressa.",
      "🍳",
    ),
    sort(
      "nina",
      "Ótima escolha ou só de vez em quando?",
      ["Ótima escolha", "Só de vez em quando"],
      [
        ["Fruta", 0],
        ["Ovo", 0],
        ["Pão integral", 0],
        ["Bolacha recheada", 1],
        ["Cereal com muito açúcar", 1],
        ["Bolo de pacote", 1],
      ],
      "Alimentos inteiros dão energia por mais tempo.",
    ),
    order(
      "tito",
      "Organize a hora do café:",
      ["Lave as mãos", "Sente-se à mesa", "Coma com calma", "Escove os dentes"],
      "Uma rotina gostosa e saudável!",
    ),
    multi(
      "mila",
      "O que combina no café da manhã?",
      ["Banana", "Ovo mexido", "Refrigerante", "Iogurte natural", "Bala"],
      [0, 1, 3],
      "Banana, ovo e iogurte são ótimos.",
    ),
    tf(
      "cadu",
      "Iogurte e frutas podem formar um bom café da manhã.",
      true,
      "Isso! É gostoso e nutritivo.",
    ),
    fill(
      "lipe",
      "O pão ___ é uma boa escolha porque tem fibras.",
      ["integral", "de bala", "doce", "frito"],
      0,
      "Pão integral tem mais fibras.",
    ),
    match(
      "nina",
      "Ligue o alimento ao grupo do café da manhã:",
      [
        ["Ovo", "Proteína"],
        ["Banana", "Fruta"],
        ["Aveia", "Energia"],
      ],
      "Um café completo junta os três grupos!",
    ),
    scenario(
      "tito",
      "No café da manhã, Ana só tomou um copo de suco bem doce e saiu correndo.",
      "O que faltou para deixar o café dela mais completo?",
      [
        "Uma proteína, como ovo ou queijo, e algo de energia",
        "Mais açúcar no suco",
        "Nada, está ótimo",
        "Só mais suco",
      ],
      0,
      "Suco sozinho passa fome rápido. Proteína e energia ajudam a segurar até o lanche.",
    ),
    tf(
      "mila",
      "Cereais muito açucarados dão uma energia que passa rápido.",
      true,
      "O açúcar dá energia rápida, mas ela acaba logo, deixando fome de novo cedo.",
    ),
    reflect(
      "cadu",
      "Se você pudesse montar o café da manhã dos seus sonhos (mas saudável), o que colocaria nele?",
    ),
  ],
  [
    concept(
      "mila",
      "Lanche da escola",
      "O lanche precisa **segurar a fome** até o almoço. Fruta, iogurte natural e sanduíche de pão integral são ótimas ideias.",
      ["Fruta e água", "Sanduíche de pão integral com queijo", "Evite bolacha recheada todo dia"],
      "Um lanche bom dá energia até a hora de brincar!",
      "🎒",
    ),
    quiz(
      "mila",
      "Qual lanche escolher para levar à escola?",
      [
        "Sanduíche de pão integral e fruta",
        "Salgadinho e refrigerante",
        "Bala e chiclete",
        "Bolacha recheada",
      ],
      0,
      "Um lanche completo deixa você com energia.",
    ),
    multi(
      "tito",
      "Quais são bons lanches?",
      ["Banana", "Iogurte natural", "Salgadinho", "Sanduíche integral"],
      [0, 1, 3],
      "Frutas, iogurte e sanduíche integral são ótimos.",
    ),
    tf("cadu", "É possível levar frutas na lancheira.", true, "Claro! Lave antes de guardar."),
    sort(
      "nina",
      "Lanche esperto ou lanche de festa?",
      ["Lanche esperto", "Lanche de festa"],
      [
        ["Banana", 0],
        ["Iogurte", 0],
        ["Sanduíche integral", 0],
        ["Salgadinho", 1],
        ["Refrigerante", 1],
        ["Bolo com recheio", 1],
      ],
      "A festa também é gostosa, mas o dia a dia pede alimentos inteiros.",
    ),
    match(
      "lipe",
      "Ligue o alimento à dica:",
      [
        ["Fruta", "Lave antes"],
        ["Sanduíche", "Guarde na lancheira"],
        ["Água", "Leve na garrafinha"],
      ],
      "Você já sabe montar a lancheira!",
    ),
    fill(
      "nina",
      "Um lanche esperto ajuda a ter ___ para as aulas.",
      ["energia", "sono", "preguiça", "fome"],
      0,
      "Energia para aprender e brincar.",
    ),
    multi(
      "mila",
      "Quais são boas opções de lanche para levar na lancheira?",
      ["Fruta", "Sanduíche integral", "Salgadinho", "Iogurte natural"],
      [0, 1, 3],
      "Fruta, sanduíche integral e iogurte são lanches espertos e gostosos.",
    ),
    scenario(
      "tito",
      "Na hora do lanche, os amigos de Pedro estão comendo salgadinho, e ele ficou com vontade de comer igual todo dia.",
      "O que ele pode fazer?",
      [
        "Comer o lanche saudável dele na maioria dos dias, e o salgadinho às vezes",
        "Comer salgadinho todos os dias também",
        "Não comer nada",
        "Ficar triste e não lanchar",
      ],
      0,
      "Não precisa proibir nada, mas o lanche esperto pode ser o de todo dia, e o salgadinho, de vez em quando.",
    ),
    reflect("nina", "O que você poderia levar de lanche esperto para a escola essa semana?"),
  ],
);

const CHEW = stop(
  "kid-2-2",
  "Mastigar com Calma",
  "😋",
  "Comer devagar, ouvir a barriguinha e cuidar dos dentes.",
  [
    concept(
      "lipe",
      "Mastigar é começar a digestão",
      "A digestão começa na **boca**! Quando mastigamos bem, a comida vira pedacinhos e o corpo aproveita melhor. Comer devagar também dá tempo da barriga avisar que estamos satisfeitos.",
      ["Mastigue bem antes de engolir", "Coma sem pressa", "Pare quando a barriga avisar"],
      "A barriga demora uns 20 minutos para avisar que está cheia.",
      "😋",
    ),
    quiz(
      "lipe",
      "Onde começa a digestão?",
      ["Na boca", "No pé", "No cabelo", "No olho"],
      0,
      "Na boca, com a mastigação!",
    ),
    tf(
      "tito",
      "Comer muito rápido é ótimo para o corpo.",
      false,
      "Comer rápido atrapalha a digestão e o aviso da barriga.",
    ),
    fill(
      "nina",
      "Para comer bem, devemos ___ bem a comida.",
      ["mastigar", "engolir", "jogar", "esconder"],
      0,
      "Mastigar bem é o primeiro passo.",
    ),
    quiz(
      "mila",
      "O que ajuda a comer com calma?",
      ["Sentar à mesa", "Correr com o prato", "Ver TV muito alto", "Comer em pé"],
      0,
      "Sentar à mesa ajuda a prestar atenção.",
    ),
    tf(
      "cadu",
      "Conversar e sorrir na mesa ajuda a comer devagar.",
      true,
      "Uma refeição alegre é uma refeição calma.",
    ),
    multi(
      "nina",
      "O que ajuda a comer com calma?",
      ["Mastigar bem", "Sentar à mesa", "Correr comendo", "Conversar tranquilo"],
      [0, 1, 3],
      "Mastigar bem, sentar à mesa e conversar tranquilo ajudam a comer com calma.",
    ),
    scenario(
      "lipe",
      "Na hora do almoço, Duda engole a comida correndo para ir brincar logo.",
      "O que ela poderia fazer diferente?",
      [
        "Comer com calma, mastigando bem",
        "Comer ainda mais rápido",
        "Não almoçar",
        "Comer andando",
      ],
      0,
      "Comer com calma ajuda a digestão e a perceber quando está satisfeita.",
    ),
    order(
      "tito",
      "Coloque em ordem uma garfada com calma:",
      [
        "Coloque uma porção pequena na boca",
        "Mastigue bem devagar",
        "Perceba o sabor",
        "Engula e respire antes da próxima",
      ],
      "Devagar e sempre: assim a refeição fica mais gostosa.",
    ),
    reflect(
      "mila",
      "Você costuma comer rápido ou devagar? O que poderia ajudar a comer com mais calma?",
    ),
  ],
  [
    concept(
      "cadu",
      "A barriguinha avisa",
      "Quando comemos, a barriga manda um recado: **estou satisfeita**. Ouvir esse recado é ótimo! Se ainda tem fome, pode repetir; se estiver cheio, pode parar.",
      [
        "Fome: barriga roncando",
        "Satisfeito: sem vontade de mais",
        "Cheio demais: barriga apertada",
      ],
      "Você não precisa terminar tudo se já está satisfeito!",
      "👂",
    ),
    match(
      "nina",
      "Ligue o sinal ao que ele quer dizer:",
      [
        ["Barriga roncando", "Estou com fome"],
        ["Sem vontade de mais", "Estou satisfeito"],
        ["Barriga apertada", "Comi demais"],
      ],
      "Você já sabe ouvir a sua barriguinha!",
    ),
    order(
      "lipe",
      "Ordene uma refeição calma:",
      [
        "Sente-se à mesa",
        "Coloque uma porção pequena",
        "Mastigue devagar",
        "Ouça a barriga antes de repetir",
      ],
      "Assim você come no ritmo do seu corpo.",
    ),
    multi(
      "tito",
      "O que atrapalha comer com calma?",
      ["Correr", "Ver TV comendo", "Sentar à mesa", "Jogar durante a refeição"],
      [0, 1, 3],
      "Distrações atrapalham a percepção da barriga.",
    ),
    tf(
      "mila",
      "Podemos parar de comer quando estamos satisfeitos.",
      true,
      "Claro! O corpo sabe do que precisa.",
    ),
    sort(
      "cadu",
      "Ajuda ou atrapalha?",
      ["Ajuda a comer com calma", "Atrapalha"],
      [
        ["Mastigar devagar", 0],
        ["Sentar à mesa", 0],
        ["Conversar", 0],
        ["Comer correndo", 1],
        ["Comer com o tablet", 1],
        ["Engolir sem mastigar", 1],
      ],
      "Atenção e calma fazem bem à digestão.",
    ),
    fill(
      "lipe",
      "Quando estou ___, é hora de parar de comer.",
      ["satisfeito", "sonolento", "sujo", "atrasado"],
      0,
      "Satisfeito é quando o corpo diz 'já chega'.",
    ),
    match(
      "nina",
      "Ligue o sinal da barriga ao que fazer:",
      [
        ["Barriga satisfeita", "Posso parar"],
        ["Ainda com fome", "Posso repetir um pouco"],
      ],
      "Ouvir a barriga é uma habilidade que a gente treina!",
    ),
    scenario(
      "cadu",
      "Gui já está satisfeito, mas o prato ainda tem comida e ele acha que precisa terminar tudo.",
      "O que ele pode fazer?",
      [
        "Ouvir a barriga e parar quando estiver satisfeito",
        "Comer tudo mesmo estando cheio",
        "Comer até passar mal",
        "Nunca parar de comer",
      ],
      0,
      "Está tudo bem deixar comida no prato quando já se está satisfeito.",
    ),
    tf(
      "tito",
      "É preciso sempre terminar tudo o que está no prato, mesmo satisfeito.",
      false,
      "Ouvir a barriga é mais importante do que terminar o prato todo.",
    ),
  ],
  [
    concept(
      "nina",
      "Cuidando dos dentes",
      "Depois de comer, escovar os dentes tira os restinhos de comida que causam **cáries**. Escove pelo menos **duas vezes por dia**, com a ajuda de um adulto quando precisar.",
      [
        "Escove de manhã e antes de dormir",
        "Use pasta com flúor, em pouca quantidade",
        "Doces grudentos pedem escovação extra",
      ],
      "Um sorriso saudável começa na escovação!",
      "🦷",
    ),
    quiz(
      "nina",
      "Quantas vezes escovar os dentes por dia, no mínimo?",
      ["Duas vezes", "Nenhuma", "Uma vez por semana", "Só quando dói"],
      0,
      "De manhã e à noite, antes de dormir.",
    ),
    tf(
      "mila",
      "Doces grudentos ajudam a formar cáries se não escovarmos.",
      true,
      "Os restinhos de doce alimentam as bactérias que estragam os dentes.",
    ),
    order(
      "lipe",
      "Ordene a escovação:",
      [
        "Coloque um pouquinho de pasta",
        "Escove todos os dentinhos",
        "Escove a língua",
        "Enxágue a boca",
      ],
      "Escovar tudo, sem pressa!",
    ),
    multi(
      "tito",
      "O que faz bem aos dentes?",
      ["Escovar", "Água", "Beber refrigerante toda hora", "Comer frutas e legumes crocantes"],
      [0, 1, 3],
      "Água, escova e alimentos crocantes ajudam.",
    ),
    sort(
      "cadu",
      "Bom para os dentes ou só de vez em quando?",
      ["Bom para os dentes", "Só de vez em quando"],
      [
        ["Água", 0],
        ["Cenoura crua", 0],
        ["Maçã", 0],
        ["Bala", 1],
        ["Refrigerante", 1],
        ["Pirulito", 1],
      ],
      "Doces são para o dia de festa, e sempre com escovação depois.",
    ),
    match(
      "nina",
      "Ligue o hábito ao motivo:",
      [
        ["Escovar", "Tira os restinhos de comida"],
        ["Fio dental", "Limpa entre os dentes"],
        ["Ir ao dentista", "Cuida do seu sorriso"],
      ],
      "Você já sabe cuidar do sorriso!",
    ),
    multi(
      "tito",
      "O que ajuda a cuidar bem dos dentes?",
      [
        "Escovar de manhã e à noite",
        "Comer doce o dia todo sem escovar",
        "Usar fio dental",
        "Ir ao dentista",
      ],
      [0, 2, 3],
      "Escovar direitinho, usar fio dental e visitar o dentista mantêm o sorriso saudável.",
    ),
    scenario(
      "cadu",
      "Depois de comer um doce grudento na festa, Vitor foi direto brincar sem escovar os dentes.",
      "O que ele deveria ter feito?",
      [
        "Escovar os dentes depois do doce",
        "Comer mais doce",
        "Não fazer nada",
        "Só enxaguar a boca com refrigerante",
      ],
      0,
      "Doces grudentos pedem escovação extra, para não deixar restinhos nos dentes.",
    ),
    reflect("mila", "Você lembra de escovar os dentes de manhã e à noite todos os dias?"),
  ],
);

const HANDS = stop(
  "kid-2-3",
  "Mãos Limpas, Comida Segura",
  "🧼",
  "Como lavar as mãos e cuidar dos alimentos para evitar dor de barriga.",
  [
    concept(
      "nina",
      "Por que lavar as mãos?",
      "Nas mãos ficam **germes** invisíveis que podem dar dor de barriga. Lavar com água e sabão antes de comer e depois de ir ao banheiro protege você e sua família.",
      ["Antes de comer", "Depois de ir ao banheiro", "Depois de brincar na rua ou com bichinhos"],
      "Cantar 'Parabéns pra você' duas vezes dá o tempo certo de lavar!",
      "🧼",
    ),
    quiz(
      "nina",
      "Quando devemos lavar as mãos?",
      ["Antes de comer", "Nunca", "Só no domingo", "Só se estiverem pretas"],
      0,
      "Antes de comer, sempre!",
    ),
    tf(
      "cadu",
      "Água e sabão são importantes para lavar as mãos.",
      true,
      "O sabão ajuda a remover os germes.",
    ),
    fill(
      "mila",
      "Lavamos as mãos com água e ___.",
      ["sabão", "tinta", "terra", "suco"],
      0,
      "Sabão, claro!",
    ),
    tf(
      "tito",
      "Só precisa lavar as mãos se estiverem visivelmente sujas.",
      false,
      "Os germes são invisíveis. Lave sempre nos momentos certos.",
    ),
    quiz(
      "lipe",
      "O que os germes podem causar?",
      ["Dor de barriga", "Superpoderes", "Cabelo colorido", "Sono bom"],
      0,
      "Por isso lavamos as mãos!",
    ),
    multi(
      "nina",
      "Quando devemos lavar as mãos?",
      ["Antes de comer", "Depois do banheiro", "Nunca", "Depois de brincar com terra"],
      [0, 1, 3],
      "Antes de comer, depois do banheiro e depois de mexer na terra: sempre lavar!",
    ),
    scenario(
      "cadu",
      "Rafa brincou no parquinho com terra e areia, e agora vai almoçar.",
      "O que ele deve fazer antes de comer?",
      [
        "Lavar bem as mãos com água e sabão",
        "Sentar e comer direto",
        "Só limpar na roupa",
        "Nada, terra não faz mal",
      ],
      0,
      "Terra pode ter germes invisíveis. Lavar as mãos antes de comer é sempre importante.",
    ),
    order(
      "mila",
      "Coloque em ordem para lavar as mãos direitinho:",
      ["Molhe as mãos", "Passe sabão", "Esfregue bem, inclusive entre os dedos", "Enxágue e seque"],
      "Assim as mãos ficam limpinhas de verdade!",
    ),
    reflect("tito", "Você lembra de lavar as mãos antes de todas as refeições?"),
  ],
  [
    concept(
      "mila",
      "Lavando as mãos em 4 passos",
      "Molhe, ensaboe, esfregue por **20 segundos**, enxágue e seque com toalha limpa. Esfregue as palmas, as costas das mãos, entre os dedos e as unhas.",
      ["Molhe as mãos", "Ensaboe bem", "Esfregue por 20 segundos", "Enxágue e seque"],
      "Os cantinhos entre os dedos escondem germes!",
      "🫧",
    ),
    order(
      "mila",
      "Ordene os passos para lavar as mãos:",
      ["Molhe as mãos", "Passe o sabão", "Esfregue por 20 segundos", "Enxágue e seque"],
      "Assim as mãos ficam limpinhas!",
    ),
    multi(
      "nina",
      "Em quais momentos lavar as mãos?",
      [
        "Antes de comer",
        "Depois do banheiro",
        "Depois de brincar com terra",
        "Antes de ver desenho",
      ],
      [0, 1, 2],
      "Comer, banheiro e terra são os momentos importantes.",
    ),
    tf(
      "cadu",
      "Secar as mãos com uma toalha limpa faz parte de lavar bem.",
      true,
      "Mãos molhadas espalham mais germes.",
    ),
    sort(
      "tito",
      "Preciso lavar as mãos?",
      ["Preciso lavar", "Não precisa agora"],
      [
        ["Antes do lanche", 0],
        ["Depois do banheiro", 0],
        ["Depois de brincar com terra", 0],
        ["Vendo desenho", 1],
        ["Lendo um livro", 1],
        ["Sentado no sofá", 1],
      ],
      "Lave sempre antes de comer e depois de se sujar.",
    ),
    match(
      "lipe",
      "Ligue o momento ao cuidado:",
      [
        ["Vou comer", "Lavar as mãos"],
        ["Brinquei com terra", "Lavar as mãos e as unhas"],
        ["Fui ao banheiro", "Lavar com sabão"],
      ],
      "Ótimo! Você já é um especialista em higiene.",
    ),
    match(
      "nina",
      "Ligue o momento ao cuidado certo:",
      [
        ["Antes de comer", "Lavar as mãos"],
        ["Depois do parquinho", "Lavar as mãos e as unhas"],
        ["Depois do banheiro", "Lavar com sabão"],
      ],
      "Cada momento pede o mesmo cuidado: água e sabão!",
    ),
    scenario(
      "mila",
      "Na hora do lanche, os amigos de Lara foram direto comer sem lavar as mãos.",
      "O que Lara pode fazer?",
      [
        "Lavar as mãos antes de comer, mesmo se os amigos não lavarem",
        "Fazer igual e não lavar",
        "Comer só metade do lanche",
        "Não comer nada",
      ],
      0,
      "Cada um cuida da própria higiene, mesmo que os amigos façam diferente.",
    ),
    tf(
      "tito",
      "Germes são tão pequenos que não dá para ver, mas podem deixar a gente doente.",
      true,
      "Por serem invisíveis, lavamos as mãos sempre, mesmo quando parecem limpas.",
    ),
    reflect("cadu", "Quantas vezes por dia você lava as mãos? Em quais momentos?"),
  ],
  [
    concept(
      "lipe",
      "Comida segura",
      "Além das mãos, os alimentos também precisam de cuidado: **lavar frutas e verduras**, guardar na geladeira o que estraga e não comer comida com cheiro ou aspecto estranho.",
      [
        "Lave frutas e verduras",
        "Guarde na geladeira o que estraga",
        "Cheiro ou gosto estranho? Avise um adulto",
      ],
      "Se a comida parece estranha, não coma. Chame um adulto!",
      "🛡️",
    ),
    quiz(
      "lipe",
      "O que fazer com uma fruta antes de comer?",
      ["Lavar", "Jogar no chão", "Pintar", "Nada"],
      0,
      "Lavar tira a sujeirinha e os germes.",
    ),
    tf(
      "tito",
      "Comida com cheiro estranho pode estar estragada.",
      true,
      "Não coma e avise um adulto!",
    ),
    order(
      "cadu",
      "Ordene o cuidado com a fruta:",
      ["Lave as mãos", "Lave a fruta", "Seque", "Coma"],
      "Primeiro as mãos, depois a fruta!",
    ),
    multi(
      "mila",
      "O que precisa ficar na geladeira?",
      ["Leite", "Iogurte", "Pão seco", "Frutas cortadas"],
      [0, 1, 3],
      "Alimentos que estragam rápido ficam na geladeira.",
    ),
    sort(
      "nina",
      "Geladeira ou pode ficar fora?",
      ["Na geladeira", "Pode ficar fora"],
      [
        ["Leite", 0],
        ["Iogurte", 0],
        ["Carne", 0],
        ["Banana", 1],
        ["Arroz cru", 1],
        ["Macarrão seco", 1],
      ],
      "Alimentos frescos e laticínios pedem geladeira.",
    ),
    match(
      "nina",
      "Ligue o cuidado ao motivo:",
      [
        ["Lavar as frutas", "Tira sujeirinhas e germes"],
        ["Guardar na geladeira", "Conserva melhor"],
        ["Avisar um adulto", "Ajuda a ficar seguro"],
      ],
      "Você é um cuidador de alimentos!",
    ),
    multi(
      "lipe",
      "O que ajuda a manter a comida segura?",
      [
        "Lavar frutas e verduras",
        "Guardar comida perecível na geladeira",
        "Comer comida com cheiro estranho",
        "Avisar um adulto se algo parecer errado",
      ],
      [0, 1, 3],
      "Lavar, guardar direito e avisar um adulto são os cuidados certos.",
    ),
    scenario(
      "tito",
      "Marina encontrou um pedaço de queijo esquecido fora da geladeira há dois dias.",
      "O que ela deve fazer?",
      [
        "Não comer e avisar um adulto",
        "Comer mesmo assim",
        "Só cheirar e comer se não sentir nada",
        "Dar para o cachorro comer",
      ],
      0,
      "Comida fora da geladeira por muito tempo pode estragar sem parecer. O melhor é avisar um adulto.",
    ),
    reflect("cadu", "O que você faria se encontrasse uma comida com cheiro estranho na geladeira?"),
  ],
);

export const KID_TRAILS: Trail[] = [
  {
    id: "kid-sabores",
    kind: "kid",
    title: "Aventura dos Sabores",
    tagline: "Cores, frutas e água",
    description: "Descubra as cores dos alimentos, conheça frutas e legumes e vire amigo da água.",
    icon: "🌈",
    guide: "cadu",
    scene: "orchard",
    units: [
      {
        id: "kid-unit-1",
        title: "Mundo das Cores",
        icon: "🌈",
        description: "Frutas, legumes e a super bebida: a água!",
        scene: "orchard",
        stops: [RAINBOW, FRUITS, WATER],
      },
    ],
  },
  {
    id: "kid-corpo",
    kind: "kid",
    title: "Corpo Forte e Feliz",
    tagline: "Rotina, dentes e higiene",
    description:
      "Aprenda a comer com calma, cuidar dos dentes e manter as mãos e a comida limpinhas.",
    icon: "💪",
    guide: "tito",
    scene: "meadow",
    units: [
      {
        id: "kid-unit-2",
        title: "Cuidando de Mim",
        icon: "💪",
        description: "Café da manhã, mastigação e higiene.",
        scene: "meadow",
        stops: [BREAKFAST, CHEW, HANDS],
      },
    ],
  },
];
