/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanhamentoRouteImport } from './routes/acompanhamento'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ComunidadesRouteImport } from './routes/comunidades'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConvitesRouteImport } from './routes/convites'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as DiretrizesRouteImport } from './routes/diretrizes'
import { Route as EspacoRouteImport } from './routes/espaco'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NinaRouteImport } from './routes/nina'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TemaDaSemanaRouteImport } from './routes/tema-da-semana'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VerificacaoRouteImport } from './routes/verificacao'
import { Route as AcompanhamentoIndexRouteImport } from './routes/acompanhamento.index'
import { Route as AcompanhamentoConsultasRouteImport } from './routes/acompanhamento.consultas'
import { Route as AcompanhamentoDiarioRouteImport } from './routes/acompanhamento.diario'
import { Route as AcompanhamentoEvolucaoRouteImport } from './routes/acompanhamento.evolucao'
import { Route as AcompanhamentoExamesRouteImport } from './routes/acompanhamento.exames'
import { Route as AcompanhamentoMensagensRouteImport } from './routes/acompanhamento.mensagens'
import { Route as AcompanhamentoMetasRouteImport } from './routes/acompanhamento.metas'
import { Route as AcompanhamentoPlanoRouteImport } from './routes/acompanhamento.plano'
import { Route as ComunidadesIndexRouteImport } from './routes/comunidades.index'
import { Route as ComunidadesSlugRouteImport } from './routes/comunidades.$slug'
import { Route as ConviteCodeRouteImport } from './routes/convite.$code'
import { Route as DesafiosIndexRouteImport } from './routes/desafios.index'
import { Route as DesafiosChallengeIdRouteImport } from './routes/desafios.$challengeId'
import { Route as PagamentoAppointmentIdRouteImport } from './routes/pagamento.$appointmentId'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAgendaRouteImport } from './routes/painel.agenda'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel.configuracoes'
import { Route as PainelFinanceiroRouteImport } from './routes/painel.financeiro'
import { Route as PainelMensagensRouteImport } from './routes/painel.mensagens'
import { Route as PerfilUserIdRouteImport } from './routes/perfil.$userId'
import { Route as PerfilConfiguracoesRouteImport } from './routes/perfil.configuracoes'
import { Route as PerfilEditarRouteImport } from './routes/perfil.editar'
import { Route as PerfilPersonalizacaoRouteImport } from './routes/perfil.personalizacao'
import { Route as ProfissionaisIndexRouteImport } from './routes/profissionais.index'
import { Route as ProfissionaisProfessionalIdRouteImport } from './routes/profissionais.$professionalId'
import { Route as ReceitasIdRouteImport } from './routes/receitas.$id'
import { Route as PainelPacientesIndexRouteImport } from './routes/painel.pacientes.index'
import { Route as PainelPacientesPatientIdRouteImport } from './routes/painel.pacientes.$patientId'
import { Route as PainelPlanosPlanIdRouteImport } from './routes/painel.planos.$planId'
import { Route as PerfilConfiguracoesIndexRouteImport } from './routes/perfil.configuracoes.index'
import { Route as PerfilConfiguracoesContaRouteImport } from './routes/perfil.configuracoes.conta'
import { Route as PerfilConfiguracoesIdiomaRouteImport } from './routes/perfil.configuracoes.idioma'
import { Route as PerfilConfiguracoesNotificacoesRouteImport } from './routes/perfil.configuracoes.notificacoes'
import { Route as PerfilConfiguracoesPrivacidadeRouteImport } from './routes/perfil.configuracoes.privacidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoRoute = AcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesRoute = ComunidadesRouteImport.update({
  id: '/comunidades',
  path: '/comunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvitesRoute = ConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretrizesRoute = DiretrizesRouteImport.update({
  id: '/diretrizes',
  path: '/diretrizes',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacoRoute = EspacoRouteImport.update({
  id: '/espaco',
  path: '/espaco',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NinaRoute = NinaRouteImport.update({
  id: '/nina',
  path: '/nina',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaDaSemanaRoute = TemaDaSemanaRouteImport.update({
  id: '/tema-da-semana',
  path: '/tema-da-semana',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificacaoRoute = VerificacaoRouteImport.update({
  id: '/verificacao',
  path: '/verificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoIndexRoute = AcompanhamentoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcompanhamentoRoute,
} as any)
const AcompanhamentoConsultasRoute = AcompanhamentoConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AcompanhamentoRoute,
} as any)
const AcompanhamentoDiarioRoute = AcompanhamentoDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AcompanhamentoRoute,
} as any)
const AcompanhamentoEvolucaoRoute = AcompanhamentoEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AcompanhamentoRoute,
} as any)
const AcompanhamentoExamesRoute = AcompanhamentoExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => AcompanhamentoRoute,
} as any)
const AcompanhamentoMensagensRoute = AcompanhamentoMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AcompanhamentoRoute,
} as any)
const AcompanhamentoMetasRoute = AcompanhamentoMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AcompanhamentoRoute,
} as any)
const AcompanhamentoPlanoRoute = AcompanhamentoPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AcompanhamentoRoute,
} as any)
const ComunidadesIndexRoute = ComunidadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComunidadesRoute,
} as any)
const ComunidadesSlugRoute = ComunidadesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComunidadesRoute,
} as any)
const ConviteCodeRoute = ConviteCodeRouteImport.update({
  id: '/convite/$code',
  path: '/convite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosIndexRoute = DesafiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesafiosRoute,
} as any)
const DesafiosChallengeIdRoute = DesafiosChallengeIdRouteImport.update({
  id: '/$challengeId',
  path: '/$challengeId',
  getParentRoute: () => DesafiosRoute,
} as any)
const PagamentoAppointmentIdRoute = PagamentoAppointmentIdRouteImport.update({
  id: '/pagamento/$appointmentId',
  path: '/pagamento/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelFinanceiroRoute = PainelFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PainelRoute,
} as any)
const PainelMensagensRoute = PainelMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => PainelRoute,
} as any)
const PerfilUserIdRoute = PerfilUserIdRouteImport.update({
  id: '/perfil/$userId',
  path: '/perfil/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilConfiguracoesRoute = PerfilConfiguracoesRouteImport.update({
  id: '/perfil/configuracoes',
  path: '/perfil/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilEditarRoute = PerfilEditarRouteImport.update({
  id: '/perfil/editar',
  path: '/perfil/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilPersonalizacaoRoute = PerfilPersonalizacaoRouteImport.update({
  id: '/perfil/personalizacao',
  path: '/perfil/personalizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisIndexRoute = ProfissionaisIndexRouteImport.update({
  id: '/profissionais/',
  path: '/profissionais/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisProfessionalIdRoute =
  ProfissionaisProfessionalIdRouteImport.update({
    id: '/profissionais/$professionalId',
    path: '/profissionais/$professionalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReceitasIdRoute = ReceitasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReceitasRoute,
} as any)
const PainelPacientesIndexRoute = PainelPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPacientesPatientIdRoute =
  PainelPacientesPatientIdRouteImport.update({
    id: '/pacientes/$patientId',
    path: '/pacientes/$patientId',
    getParentRoute: () => PainelRoute,
  } as any)
const PainelPlanosPlanIdRoute = PainelPlanosPlanIdRouteImport.update({
  id: '/planos/$planId',
  path: '/planos/$planId',
  getParentRoute: () => PainelRoute,
} as any)
const PerfilConfiguracoesIndexRoute =
  PerfilConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PerfilConfiguracoesRoute,
  } as any)
const PerfilConfiguracoesContaRoute =
  PerfilConfiguracoesContaRouteImport.update({
    id: '/conta',
    path: '/conta',
    getParentRoute: () => PerfilConfiguracoesRoute,
  } as any)
const PerfilConfiguracoesIdiomaRoute =
  PerfilConfiguracoesIdiomaRouteImport.update({
    id: '/idioma',
    path: '/idioma',
    getParentRoute: () => PerfilConfiguracoesRoute,
  } as any)
const PerfilConfiguracoesNotificacoesRoute =
  PerfilConfiguracoesNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => PerfilConfiguracoesRoute,
  } as any)
const PerfilConfiguracoesPrivacidadeRoute =
  PerfilConfiguracoesPrivacidadeRouteImport.update({
    id: '/privacidade',
    path: '/privacidade',
    getParentRoute: () => PerfilConfiguracoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRouteWithChildren
  '/admin': typeof AdminRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/cadastro': typeof CadastroRoute
  '/comunidades': typeof ComunidadesRouteWithChildren
  '/contato': typeof ContatoRoute
  '/convites': typeof ConvitesRoute
  '/desafios': typeof DesafiosRouteWithChildren
  '/diretrizes': typeof DiretrizesRoute
  '/espaco': typeof EspacoRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/nina': typeof NinaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sobre': typeof SobreRoute
  '/tema-da-semana': typeof TemaDaSemanaRoute
  '/termos': typeof TermosRoute
  '/verificacao': typeof VerificacaoRoute
  '/acompanhamento/consultas': typeof AcompanhamentoConsultasRoute
  '/acompanhamento/diario': typeof AcompanhamentoDiarioRoute
  '/acompanhamento/evolucao': typeof AcompanhamentoEvolucaoRoute
  '/acompanhamento/exames': typeof AcompanhamentoExamesRoute
  '/acompanhamento/mensagens': typeof AcompanhamentoMensagensRoute
  '/acompanhamento/metas': typeof AcompanhamentoMetasRoute
  '/acompanhamento/plano': typeof AcompanhamentoPlanoRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/desafios/$challengeId': typeof DesafiosChallengeIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/mensagens': typeof PainelMensagensRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRouteWithChildren
  '/perfil/editar': typeof PerfilEditarRoute
  '/perfil/personalizacao': typeof PerfilPersonalizacaoRoute
  '/profissionais/$professionalId': typeof ProfissionaisProfessionalIdRoute
  '/receitas/$id': typeof ReceitasIdRoute
  '/acompanhamento/': typeof AcompanhamentoIndexRoute
  '/comunidades/': typeof ComunidadesIndexRoute
  '/desafios/': typeof DesafiosIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/profissionais/': typeof ProfissionaisIndexRoute
  '/painel/pacientes/$patientId': typeof PainelPacientesPatientIdRoute
  '/painel/planos/$planId': typeof PainelPlanosPlanIdRoute
  '/perfil/configuracoes/conta': typeof PerfilConfiguracoesContaRoute
  '/perfil/configuracoes/idioma': typeof PerfilConfiguracoesIdiomaRoute
  '/perfil/configuracoes/notificacoes': typeof PerfilConfiguracoesNotificacoesRoute
  '/perfil/configuracoes/privacidade': typeof PerfilConfiguracoesPrivacidadeRoute
  '/painel/pacientes/': typeof PainelPacientesIndexRoute
  '/perfil/configuracoes/': typeof PerfilConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/convites': typeof ConvitesRoute
  '/diretrizes': typeof DiretrizesRoute
  '/espaco': typeof EspacoRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/nina': typeof NinaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sobre': typeof SobreRoute
  '/tema-da-semana': typeof TemaDaSemanaRoute
  '/termos': typeof TermosRoute
  '/verificacao': typeof VerificacaoRoute
  '/acompanhamento/consultas': typeof AcompanhamentoConsultasRoute
  '/acompanhamento/diario': typeof AcompanhamentoDiarioRoute
  '/acompanhamento/evolucao': typeof AcompanhamentoEvolucaoRoute
  '/acompanhamento/exames': typeof AcompanhamentoExamesRoute
  '/acompanhamento/mensagens': typeof AcompanhamentoMensagensRoute
  '/acompanhamento/metas': typeof AcompanhamentoMetasRoute
  '/acompanhamento/plano': typeof AcompanhamentoPlanoRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/desafios/$challengeId': typeof DesafiosChallengeIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/mensagens': typeof PainelMensagensRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/perfil/personalizacao': typeof PerfilPersonalizacaoRoute
  '/profissionais/$professionalId': typeof ProfissionaisProfessionalIdRoute
  '/receitas/$id': typeof ReceitasIdRoute
  '/acompanhamento': typeof AcompanhamentoIndexRoute
  '/comunidades': typeof ComunidadesIndexRoute
  '/desafios': typeof DesafiosIndexRoute
  '/painel': typeof PainelIndexRoute
  '/profissionais': typeof ProfissionaisIndexRoute
  '/painel/pacientes/$patientId': typeof PainelPacientesPatientIdRoute
  '/painel/planos/$planId': typeof PainelPlanosPlanIdRoute
  '/perfil/configuracoes/conta': typeof PerfilConfiguracoesContaRoute
  '/perfil/configuracoes/idioma': typeof PerfilConfiguracoesIdiomaRoute
  '/perfil/configuracoes/notificacoes': typeof PerfilConfiguracoesNotificacoesRoute
  '/perfil/configuracoes/privacidade': typeof PerfilConfiguracoesPrivacidadeRoute
  '/painel/pacientes': typeof PainelPacientesIndexRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRouteWithChildren
  '/admin': typeof AdminRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/cadastro': typeof CadastroRoute
  '/comunidades': typeof ComunidadesRouteWithChildren
  '/contato': typeof ContatoRoute
  '/convites': typeof ConvitesRoute
  '/desafios': typeof DesafiosRouteWithChildren
  '/diretrizes': typeof DiretrizesRoute
  '/espaco': typeof EspacoRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/nina': typeof NinaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sobre': typeof SobreRoute
  '/tema-da-semana': typeof TemaDaSemanaRoute
  '/termos': typeof TermosRoute
  '/verificacao': typeof VerificacaoRoute
  '/acompanhamento/consultas': typeof AcompanhamentoConsultasRoute
  '/acompanhamento/diario': typeof AcompanhamentoDiarioRoute
  '/acompanhamento/evolucao': typeof AcompanhamentoEvolucaoRoute
  '/acompanhamento/exames': typeof AcompanhamentoExamesRoute
  '/acompanhamento/mensagens': typeof AcompanhamentoMensagensRoute
  '/acompanhamento/metas': typeof AcompanhamentoMetasRoute
  '/acompanhamento/plano': typeof AcompanhamentoPlanoRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/desafios/$challengeId': typeof DesafiosChallengeIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/mensagens': typeof PainelMensagensRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRouteWithChildren
  '/perfil/editar': typeof PerfilEditarRoute
  '/perfil/personalizacao': typeof PerfilPersonalizacaoRoute
  '/profissionais/$professionalId': typeof ProfissionaisProfessionalIdRoute
  '/receitas/$id': typeof ReceitasIdRoute
  '/acompanhamento/': typeof AcompanhamentoIndexRoute
  '/comunidades/': typeof ComunidadesIndexRoute
  '/desafios/': typeof DesafiosIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/profissionais/': typeof ProfissionaisIndexRoute
  '/painel/pacientes/$patientId': typeof PainelPacientesPatientIdRoute
  '/painel/planos/$planId': typeof PainelPlanosPlanIdRoute
  '/perfil/configuracoes/conta': typeof PerfilConfiguracoesContaRoute
  '/perfil/configuracoes/idioma': typeof PerfilConfiguracoesIdiomaRoute
  '/perfil/configuracoes/notificacoes': typeof PerfilConfiguracoesNotificacoesRoute
  '/perfil/configuracoes/privacidade': typeof PerfilConfiguracoesPrivacidadeRoute
  '/painel/pacientes/': typeof PainelPacientesIndexRoute
  '/perfil/configuracoes/': typeof PerfilConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhamento'
    | '/admin'
    | '/apresentacao'
    | '/cadastro'
    | '/comunidades'
    | '/contato'
    | '/convites'
    | '/desafios'
    | '/diretrizes'
    | '/espaco'
    | '/explorar'
    | '/login'
    | '/nina'
    | '/notificacoes'
    | '/painel'
    | '/privacidade'
    | '/receitas'
    | '/recuperar-senha'
    | '/sobre'
    | '/tema-da-semana'
    | '/termos'
    | '/verificacao'
    | '/acompanhamento/consultas'
    | '/acompanhamento/diario'
    | '/acompanhamento/evolucao'
    | '/acompanhamento/exames'
    | '/acompanhamento/mensagens'
    | '/acompanhamento/metas'
    | '/acompanhamento/plano'
    | '/comunidades/$slug'
    | '/convite/$code'
    | '/desafios/$challengeId'
    | '/pagamento/$appointmentId'
    | '/painel/agenda'
    | '/painel/configuracoes'
    | '/painel/financeiro'
    | '/painel/mensagens'
    | '/perfil/$userId'
    | '/perfil/configuracoes'
    | '/perfil/editar'
    | '/perfil/personalizacao'
    | '/profissionais/$professionalId'
    | '/receitas/$id'
    | '/acompanhamento/'
    | '/comunidades/'
    | '/desafios/'
    | '/painel/'
    | '/profissionais/'
    | '/painel/pacientes/$patientId'
    | '/painel/planos/$planId'
    | '/perfil/configuracoes/conta'
    | '/perfil/configuracoes/idioma'
    | '/perfil/configuracoes/notificacoes'
    | '/perfil/configuracoes/privacidade'
    | '/painel/pacientes/'
    | '/perfil/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apresentacao'
    | '/cadastro'
    | '/contato'
    | '/convites'
    | '/diretrizes'
    | '/espaco'
    | '/explorar'
    | '/login'
    | '/nina'
    | '/notificacoes'
    | '/privacidade'
    | '/receitas'
    | '/recuperar-senha'
    | '/sobre'
    | '/tema-da-semana'
    | '/termos'
    | '/verificacao'
    | '/acompanhamento/consultas'
    | '/acompanhamento/diario'
    | '/acompanhamento/evolucao'
    | '/acompanhamento/exames'
    | '/acompanhamento/mensagens'
    | '/acompanhamento/metas'
    | '/acompanhamento/plano'
    | '/comunidades/$slug'
    | '/convite/$code'
    | '/desafios/$challengeId'
    | '/pagamento/$appointmentId'
    | '/painel/agenda'
    | '/painel/configuracoes'
    | '/painel/financeiro'
    | '/painel/mensagens'
    | '/perfil/$userId'
    | '/perfil/editar'
    | '/perfil/personalizacao'
    | '/profissionais/$professionalId'
    | '/receitas/$id'
    | '/acompanhamento'
    | '/comunidades'
    | '/desafios'
    | '/painel'
    | '/profissionais'
    | '/painel/pacientes/$patientId'
    | '/painel/planos/$planId'
    | '/perfil/configuracoes/conta'
    | '/perfil/configuracoes/idioma'
    | '/perfil/configuracoes/notificacoes'
    | '/perfil/configuracoes/privacidade'
    | '/painel/pacientes'
    | '/perfil/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/acompanhamento'
    | '/admin'
    | '/apresentacao'
    | '/cadastro'
    | '/comunidades'
    | '/contato'
    | '/convites'
    | '/desafios'
    | '/diretrizes'
    | '/espaco'
    | '/explorar'
    | '/login'
    | '/nina'
    | '/notificacoes'
    | '/painel'
    | '/privacidade'
    | '/receitas'
    | '/recuperar-senha'
    | '/sobre'
    | '/tema-da-semana'
    | '/termos'
    | '/verificacao'
    | '/acompanhamento/consultas'
    | '/acompanhamento/diario'
    | '/acompanhamento/evolucao'
    | '/acompanhamento/exames'
    | '/acompanhamento/mensagens'
    | '/acompanhamento/metas'
    | '/acompanhamento/plano'
    | '/comunidades/$slug'
    | '/convite/$code'
    | '/desafios/$challengeId'
    | '/pagamento/$appointmentId'
    | '/painel/agenda'
    | '/painel/configuracoes'
    | '/painel/financeiro'
    | '/painel/mensagens'
    | '/perfil/$userId'
    | '/perfil/configuracoes'
    | '/perfil/editar'
    | '/perfil/personalizacao'
    | '/profissionais/$professionalId'
    | '/receitas/$id'
    | '/acompanhamento/'
    | '/comunidades/'
    | '/desafios/'
    | '/painel/'
    | '/profissionais/'
    | '/painel/pacientes/$patientId'
    | '/painel/planos/$planId'
    | '/perfil/configuracoes/conta'
    | '/perfil/configuracoes/idioma'
    | '/perfil/configuracoes/notificacoes'
    | '/perfil/configuracoes/privacidade'
    | '/painel/pacientes/'
    | '/perfil/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanhamentoRoute: typeof AcompanhamentoRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
  CadastroRoute: typeof CadastroRoute
  ComunidadesRoute: typeof ComunidadesRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ConvitesRoute: typeof ConvitesRoute
  DesafiosRoute: typeof DesafiosRouteWithChildren
  DiretrizesRoute: typeof DiretrizesRoute
  EspacoRoute: typeof EspacoRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  NinaRoute: typeof NinaRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PainelRoute: typeof PainelRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReceitasRoute: typeof ReceitasRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  SobreRoute: typeof SobreRoute
  TemaDaSemanaRoute: typeof TemaDaSemanaRoute
  TermosRoute: typeof TermosRoute
  VerificacaoRoute: typeof VerificacaoRoute
  ConviteCodeRoute: typeof ConviteCodeRoute
  PagamentoAppointmentIdRoute: typeof PagamentoAppointmentIdRoute
  PerfilUserIdRoute: typeof PerfilUserIdRoute
  PerfilConfiguracoesRoute: typeof PerfilConfiguracoesRouteWithChildren
  PerfilEditarRoute: typeof PerfilEditarRoute
  PerfilPersonalizacaoRoute: typeof PerfilPersonalizacaoRoute
  ProfissionaisProfessionalIdRoute: typeof ProfissionaisProfessionalIdRoute
  ProfissionaisIndexRoute: typeof ProfissionaisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento': {
      id: '/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AcompanhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades': {
      id: '/comunidades'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof ComunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convites': {
      id: '/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof ConvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretrizes': {
      id: '/diretrizes'
      path: '/diretrizes'
      fullPath: '/diretrizes'
      preLoaderRoute: typeof DiretrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espaco': {
      id: '/espaco'
      path: '/espaco'
      fullPath: '/espaco'
      preLoaderRoute: typeof EspacoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nina': {
      id: '/nina'
      path: '/nina'
      fullPath: '/nina'
      preLoaderRoute: typeof NinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema-da-semana': {
      id: '/tema-da-semana'
      path: '/tema-da-semana'
      fullPath: '/tema-da-semana'
      preLoaderRoute: typeof TemaDaSemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificacao': {
      id: '/verificacao'
      path: '/verificacao'
      fullPath: '/verificacao'
      preLoaderRoute: typeof VerificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento/': {
      id: '/acompanhamento/'
      path: '/'
      fullPath: '/acompanhamento/'
      preLoaderRoute: typeof AcompanhamentoIndexRouteImport
      parentRoute: typeof AcompanhamentoRoute
    }
    '/acompanhamento/consultas': {
      id: '/acompanhamento/consultas'
      path: '/consultas'
      fullPath: '/acompanhamento/consultas'
      preLoaderRoute: typeof AcompanhamentoConsultasRouteImport
      parentRoute: typeof AcompanhamentoRoute
    }
    '/acompanhamento/diario': {
      id: '/acompanhamento/diario'
      path: '/diario'
      fullPath: '/acompanhamento/diario'
      preLoaderRoute: typeof AcompanhamentoDiarioRouteImport
      parentRoute: typeof AcompanhamentoRoute
    }
    '/acompanhamento/evolucao': {
      id: '/acompanhamento/evolucao'
      path: '/evolucao'
      fullPath: '/acompanhamento/evolucao'
      preLoaderRoute: typeof AcompanhamentoEvolucaoRouteImport
      parentRoute: typeof AcompanhamentoRoute
    }
    '/acompanhamento/exames': {
      id: '/acompanhamento/exames'
      path: '/exames'
      fullPath: '/acompanhamento/exames'
      preLoaderRoute: typeof AcompanhamentoExamesRouteImport
      parentRoute: typeof AcompanhamentoRoute
    }
    '/acompanhamento/mensagens': {
      id: '/acompanhamento/mensagens'
      path: '/mensagens'
      fullPath: '/acompanhamento/mensagens'
      preLoaderRoute: typeof AcompanhamentoMensagensRouteImport
      parentRoute: typeof AcompanhamentoRoute
    }
    '/acompanhamento/metas': {
      id: '/acompanhamento/metas'
      path: '/metas'
      fullPath: '/acompanhamento/metas'
      preLoaderRoute: typeof AcompanhamentoMetasRouteImport
      parentRoute: typeof AcompanhamentoRoute
    }
    '/acompanhamento/plano': {
      id: '/acompanhamento/plano'
      path: '/plano'
      fullPath: '/acompanhamento/plano'
      preLoaderRoute: typeof AcompanhamentoPlanoRouteImport
      parentRoute: typeof AcompanhamentoRoute
    }
    '/comunidades/': {
      id: '/comunidades/'
      path: '/'
      fullPath: '/comunidades/'
      preLoaderRoute: typeof ComunidadesIndexRouteImport
      parentRoute: typeof ComunidadesRoute
    }
    '/comunidades/$slug': {
      id: '/comunidades/$slug'
      path: '/$slug'
      fullPath: '/comunidades/$slug'
      preLoaderRoute: typeof ComunidadesSlugRouteImport
      parentRoute: typeof ComunidadesRoute
    }
    '/convite/$code': {
      id: '/convite/$code'
      path: '/convite/$code'
      fullPath: '/convite/$code'
      preLoaderRoute: typeof ConviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios/': {
      id: '/desafios/'
      path: '/'
      fullPath: '/desafios/'
      preLoaderRoute: typeof DesafiosIndexRouteImport
      parentRoute: typeof DesafiosRoute
    }
    '/desafios/$challengeId': {
      id: '/desafios/$challengeId'
      path: '/$challengeId'
      fullPath: '/desafios/$challengeId'
      preLoaderRoute: typeof DesafiosChallengeIdRouteImport
      parentRoute: typeof DesafiosRoute
    }
    '/pagamento/$appointmentId': {
      id: '/pagamento/$appointmentId'
      path: '/pagamento/$appointmentId'
      fullPath: '/pagamento/$appointmentId'
      preLoaderRoute: typeof PagamentoAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/agenda': {
      id: '/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/financeiro': {
      id: '/painel/financeiro'
      path: '/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof PainelFinanceiroRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/mensagens': {
      id: '/painel/mensagens'
      path: '/mensagens'
      fullPath: '/painel/mensagens'
      preLoaderRoute: typeof PainelMensagensRouteImport
      parentRoute: typeof PainelRoute
    }
    '/perfil/$userId': {
      id: '/perfil/$userId'
      path: '/perfil/$userId'
      fullPath: '/perfil/$userId'
      preLoaderRoute: typeof PerfilUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/configuracoes': {
      id: '/perfil/configuracoes'
      path: '/perfil/configuracoes'
      fullPath: '/perfil/configuracoes'
      preLoaderRoute: typeof PerfilConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/editar': {
      id: '/perfil/editar'
      path: '/perfil/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof PerfilEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/personalizacao': {
      id: '/perfil/personalizacao'
      path: '/perfil/personalizacao'
      fullPath: '/perfil/personalizacao'
      preLoaderRoute: typeof PerfilPersonalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais/': {
      id: '/profissionais/'
      path: '/profissionais'
      fullPath: '/profissionais/'
      preLoaderRoute: typeof ProfissionaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais/$professionalId': {
      id: '/profissionais/$professionalId'
      path: '/profissionais/$professionalId'
      fullPath: '/profissionais/$professionalId'
      preLoaderRoute: typeof ProfissionaisProfessionalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas/$id': {
      id: '/receitas/$id'
      path: '/$id'
      fullPath: '/receitas/$id'
      preLoaderRoute: typeof ReceitasIdRouteImport
      parentRoute: typeof ReceitasRoute
    }
    '/painel/pacientes/': {
      id: '/painel/pacientes/'
      path: '/pacientes'
      fullPath: '/painel/pacientes/'
      preLoaderRoute: typeof PainelPacientesIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/pacientes/$patientId': {
      id: '/painel/pacientes/$patientId'
      path: '/pacientes/$patientId'
      fullPath: '/painel/pacientes/$patientId'
      preLoaderRoute: typeof PainelPacientesPatientIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/planos/$planId': {
      id: '/painel/planos/$planId'
      path: '/planos/$planId'
      fullPath: '/painel/planos/$planId'
      preLoaderRoute: typeof PainelPlanosPlanIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/perfil/configuracoes/': {
      id: '/perfil/configuracoes/'
      path: '/'
      fullPath: '/perfil/configuracoes/'
      preLoaderRoute: typeof PerfilConfiguracoesIndexRouteImport
      parentRoute: typeof PerfilConfiguracoesRoute
    }
    '/perfil/configuracoes/conta': {
      id: '/perfil/configuracoes/conta'
      path: '/conta'
      fullPath: '/perfil/configuracoes/conta'
      preLoaderRoute: typeof PerfilConfiguracoesContaRouteImport
      parentRoute: typeof PerfilConfiguracoesRoute
    }
    '/perfil/configuracoes/idioma': {
      id: '/perfil/configuracoes/idioma'
      path: '/idioma'
      fullPath: '/perfil/configuracoes/idioma'
      preLoaderRoute: typeof PerfilConfiguracoesIdiomaRouteImport
      parentRoute: typeof PerfilConfiguracoesRoute
    }
    '/perfil/configuracoes/notificacoes': {
      id: '/perfil/configuracoes/notificacoes'
      path: '/notificacoes'
      fullPath: '/perfil/configuracoes/notificacoes'
      preLoaderRoute: typeof PerfilConfiguracoesNotificacoesRouteImport
      parentRoute: typeof PerfilConfiguracoesRoute
    }
    '/perfil/configuracoes/privacidade': {
      id: '/perfil/configuracoes/privacidade'
      path: '/privacidade'
      fullPath: '/perfil/configuracoes/privacidade'
      preLoaderRoute: typeof PerfilConfiguracoesPrivacidadeRouteImport
      parentRoute: typeof PerfilConfiguracoesRoute
    }
  }
}

interface AcompanhamentoRouteChildren {
  AcompanhamentoConsultasRoute: typeof AcompanhamentoConsultasRoute
  AcompanhamentoDiarioRoute: typeof AcompanhamentoDiarioRoute
  AcompanhamentoEvolucaoRoute: typeof AcompanhamentoEvolucaoRoute
  AcompanhamentoExamesRoute: typeof AcompanhamentoExamesRoute
  AcompanhamentoMensagensRoute: typeof AcompanhamentoMensagensRoute
  AcompanhamentoMetasRoute: typeof AcompanhamentoMetasRoute
  AcompanhamentoPlanoRoute: typeof AcompanhamentoPlanoRoute
  AcompanhamentoIndexRoute: typeof AcompanhamentoIndexRoute
}

const AcompanhamentoRouteChildren: AcompanhamentoRouteChildren = {
  AcompanhamentoConsultasRoute: AcompanhamentoConsultasRoute,
  AcompanhamentoDiarioRoute: AcompanhamentoDiarioRoute,
  AcompanhamentoEvolucaoRoute: AcompanhamentoEvolucaoRoute,
  AcompanhamentoExamesRoute: AcompanhamentoExamesRoute,
  AcompanhamentoMensagensRoute: AcompanhamentoMensagensRoute,
  AcompanhamentoMetasRoute: AcompanhamentoMetasRoute,
  AcompanhamentoPlanoRoute: AcompanhamentoPlanoRoute,
  AcompanhamentoIndexRoute: AcompanhamentoIndexRoute,
}

const AcompanhamentoRouteWithChildren = AcompanhamentoRoute._addFileChildren(
  AcompanhamentoRouteChildren,
)

interface ComunidadesRouteChildren {
  ComunidadesSlugRoute: typeof ComunidadesSlugRoute
  ComunidadesIndexRoute: typeof ComunidadesIndexRoute
}

const ComunidadesRouteChildren: ComunidadesRouteChildren = {
  ComunidadesSlugRoute: ComunidadesSlugRoute,
  ComunidadesIndexRoute: ComunidadesIndexRoute,
}

const ComunidadesRouteWithChildren = ComunidadesRoute._addFileChildren(
  ComunidadesRouteChildren,
)

interface DesafiosRouteChildren {
  DesafiosChallengeIdRoute: typeof DesafiosChallengeIdRoute
  DesafiosIndexRoute: typeof DesafiosIndexRoute
}

const DesafiosRouteChildren: DesafiosRouteChildren = {
  DesafiosChallengeIdRoute: DesafiosChallengeIdRoute,
  DesafiosIndexRoute: DesafiosIndexRoute,
}

const DesafiosRouteWithChildren = DesafiosRoute._addFileChildren(
  DesafiosRouteChildren,
)

interface PainelRouteChildren {
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelFinanceiroRoute: typeof PainelFinanceiroRoute
  PainelMensagensRoute: typeof PainelMensagensRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelPacientesPatientIdRoute: typeof PainelPacientesPatientIdRoute
  PainelPlanosPlanIdRoute: typeof PainelPlanosPlanIdRoute
  PainelPacientesIndexRoute: typeof PainelPacientesIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAgendaRoute: PainelAgendaRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelFinanceiroRoute: PainelFinanceiroRoute,
  PainelMensagensRoute: PainelMensagensRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelPacientesPatientIdRoute: PainelPacientesPatientIdRoute,
  PainelPlanosPlanIdRoute: PainelPlanosPlanIdRoute,
  PainelPacientesIndexRoute: PainelPacientesIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

interface ReceitasRouteChildren {
  ReceitasIdRoute: typeof ReceitasIdRoute
}

const ReceitasRouteChildren: ReceitasRouteChildren = {
  ReceitasIdRoute: ReceitasIdRoute,
}

const ReceitasRouteWithChildren = ReceitasRoute._addFileChildren(
  ReceitasRouteChildren,
)

interface PerfilConfiguracoesRouteChildren {
  PerfilConfiguracoesContaRoute: typeof PerfilConfiguracoesContaRoute
  PerfilConfiguracoesIdiomaRoute: typeof PerfilConfiguracoesIdiomaRoute
  PerfilConfiguracoesNotificacoesRoute: typeof PerfilConfiguracoesNotificacoesRoute
  PerfilConfiguracoesPrivacidadeRoute: typeof PerfilConfiguracoesPrivacidadeRoute
  PerfilConfiguracoesIndexRoute: typeof PerfilConfiguracoesIndexRoute
}

const PerfilConfiguracoesRouteChildren: PerfilConfiguracoesRouteChildren = {
  PerfilConfiguracoesContaRoute: PerfilConfiguracoesContaRoute,
  PerfilConfiguracoesIdiomaRoute: PerfilConfiguracoesIdiomaRoute,
  PerfilConfiguracoesNotificacoesRoute: PerfilConfiguracoesNotificacoesRoute,
  PerfilConfiguracoesPrivacidadeRoute: PerfilConfiguracoesPrivacidadeRoute,
  PerfilConfiguracoesIndexRoute: PerfilConfiguracoesIndexRoute,
}

const PerfilConfiguracoesRouteWithChildren =
  PerfilConfiguracoesRoute._addFileChildren(PerfilConfiguracoesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanhamentoRoute: AcompanhamentoRouteWithChildren,
  AdminRoute: AdminRoute,
  ApresentacaoRoute: ApresentacaoRoute,
  CadastroRoute: CadastroRoute,
  ComunidadesRoute: ComunidadesRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ConvitesRoute: ConvitesRoute,
  DesafiosRoute: DesafiosRouteWithChildren,
  DiretrizesRoute: DiretrizesRoute,
  EspacoRoute: EspacoRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  NinaRoute: NinaRoute,
  NotificacoesRoute: NotificacoesRoute,
  PainelRoute: PainelRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ReceitasRoute: ReceitasRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  SobreRoute: SobreRoute,
  TemaDaSemanaRoute: TemaDaSemanaRoute,
  TermosRoute: TermosRoute,
  VerificacaoRoute: VerificacaoRoute,
  ConviteCodeRoute: ConviteCodeRoute,
  PagamentoAppointmentIdRoute: PagamentoAppointmentIdRoute,
  PerfilUserIdRoute: PerfilUserIdRoute,
  PerfilConfiguracoesRoute: PerfilConfiguracoesRouteWithChildren,
  PerfilEditarRoute: PerfilEditarRoute,
  PerfilPersonalizacaoRoute: PerfilPersonalizacaoRoute,
  ProfissionaisProfessionalIdRoute: ProfissionaisProfessionalIdRoute,
  ProfissionaisIndexRoute: ProfissionaisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
