-- =============================================================================
-- NutriConnect — prontuário, antropometria, alimentos, plano alimentar,
-- metas, diário alimentar, mensagens e documentos.
--
-- Regra geral de acesso:
--   * o paciente lê tudo o que é dele (exceto notas clínicas privadas e rascunhos);
--   * o profissional escreve com vínculo ativo e continua lendo o que registrou
--     mesmo após o fim do vínculo (guarda de prontuário);
--   * dados gerados pelo próprio paciente (diário, metas, medidas, exames) ficam
--     visíveis a todos os profissionais com vínculo ativo.
-- =============================================================================

create type public.meal_plan_status as enum ('rascunho', 'ativo', 'arquivado');
create type public.document_kind as enum ('exame', 'documento', 'plano', 'outro');

-- ---------------------------------------------------------------------------
-- Anamnese (uma por par paciente/profissional, estrutura em JSON tipada no app)
-- ---------------------------------------------------------------------------
create table public.anamneses (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  professional_id uuid not null references public.professionals (user_id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (patient_id, professional_id)
);
create trigger anamneses_updated_at before update on public.anamneses
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Evolução clínica (SOAP) — sempre privada ao profissional autor
-- ---------------------------------------------------------------------------
create table public.clinical_notes (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  professional_id uuid not null references public.professionals (user_id) on delete cascade,
  appointment_id uuid references public.appointments (id) on delete set null,
  subjective text,
  objective text,
  assessment text,
  plan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger clinical_notes_updated_at before update on public.clinical_notes
  for each row execute function public.set_updated_at();
create index clinical_notes_patient_idx on public.clinical_notes (patient_id, professional_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Antropometria
-- ---------------------------------------------------------------------------
create table public.anthropometrics (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  -- null = autorregistro do paciente (apenas peso/cintura).
  professional_id uuid references public.professionals (user_id) on delete set null,
  appointment_id uuid references public.appointments (id) on delete set null,
  measured_at date not null default current_date,
  weight_kg numeric(5, 2) check (weight_kg between 1 and 500),
  height_cm numeric(5, 1) check (height_cm between 30 and 260),
  -- Circunferências (cm): waist, hip, arm, calf, neck, chest, thigh, abdomen.
  circumferences jsonb not null default '{}'::jsonb,
  -- Dobras cutâneas (mm): triceps, biceps, subscapular, suprailiac, abdominal, thigh, chest, midaxillary.
  skinfolds jsonb not null default '{}'::jsonb,
  body_fat_protocol text, -- jp3, jp7, durnin, bioimpedancia, manual
  body_fat_pct numeric(4, 1) check (body_fat_pct between 1 and 80),
  activity_factor numeric(3, 2),
  bmr_kcal integer,
  tdee_kcal integer,
  bmr_formula text, -- harris_benedict, mifflin, fao_who
  notes text,
  created_at timestamptz not null default now()
);
create index anthropometrics_patient_idx on public.anthropometrics (patient_id, measured_at);

-- ---------------------------------------------------------------------------
-- Alimentos (TACO + alimentos próprios do profissional). Valores por 100 g.
-- ---------------------------------------------------------------------------
create table public.foods (
  id bigint generated by default as identity primary key,
  source text not null default 'TACO' check (source in ('TACO', 'custom')),
  source_code text,
  owner_id uuid references public.professionals (user_id) on delete cascade,
  name text not null,
  category text not null,
  kcal numeric(7, 2) not null default 0,
  protein_g numeric(7, 2) not null default 0,
  carbs_g numeric(7, 2) not null default 0,
  fat_g numeric(7, 2) not null default 0,
  fiber_g numeric(7, 2),
  sodium_mg numeric(8, 2),
  calcium_mg numeric(8, 2),
  iron_mg numeric(7, 2),
  -- Medidas caseiras: [{ "name": "colher de sopa", "grams": 25 }]
  household_measures jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  check ((source = 'custom') = (owner_id is not null))
);
create extension if not exists pg_trgm with schema extensions;
create index foods_name_trgm_idx on public.foods using gin (lower(name) extensions.gin_trgm_ops);
create unique index foods_source_code_idx on public.foods (source, source_code) where source_code is not null;

-- ---------------------------------------------------------------------------
-- Plano alimentar
-- ---------------------------------------------------------------------------
create table public.meal_plans (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  professional_id uuid not null references public.professionals (user_id) on delete cascade,
  title text not null default 'Plano alimentar',
  status public.meal_plan_status not null default 'rascunho',
  starts_on date,
  ends_on date,
  target_kcal integer,
  target_protein_g integer,
  target_carbs_g integer,
  target_fat_g integer,
  guidelines text, -- orientações gerais que o paciente lê
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger meal_plans_updated_at before update on public.meal_plans
  for each row execute function public.set_updated_at();
create unique index meal_plans_one_active
  on public.meal_plans (patient_id, professional_id) where status = 'ativo';
create index meal_plans_patient_idx on public.meal_plans (patient_id, status);

create table public.meal_plan_meals (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.meal_plans (id) on delete cascade,
  name text not null,
  time_of_day time,
  position integer not null default 0,
  notes text
);
create index meal_plan_meals_plan_idx on public.meal_plan_meals (plan_id, position);

create table public.meal_plan_items (
  id uuid primary key default gen_random_uuid(),
  meal_id uuid not null references public.meal_plan_meals (id) on delete cascade,
  -- Substituição de outro item (mesma refeição).
  substitute_of uuid references public.meal_plan_items (id) on delete cascade,
  food_id bigint references public.foods (id) on delete set null,
  food_name text not null, -- cópia do nome (preserva o plano se o alimento mudar)
  quantity_g numeric(7, 1) not null check (quantity_g > 0),
  household_measure text, -- ex.: "2 colheres de sopa"
  kcal numeric(7, 1) not null default 0,
  protein_g numeric(6, 1) not null default 0,
  carbs_g numeric(6, 1) not null default 0,
  fat_g numeric(6, 1) not null default 0,
  position integer not null default 0,
  notes text
);
create index meal_plan_items_meal_idx on public.meal_plan_items (meal_id, position);

-- ---------------------------------------------------------------------------
-- Metas e check-ins diários
-- ---------------------------------------------------------------------------
create table public.goals (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  professional_id uuid references public.professionals (user_id) on delete set null,
  title text not null,
  description text,
  icon text not null default '🎯',
  target_value numeric(7, 1) not null default 1 check (target_value > 0),
  unit text not null default 'vez',
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index goals_patient_idx on public.goals (patient_id, active);

create table public.goal_checkins (
  goal_id uuid not null references public.goals (id) on delete cascade,
  patient_id uuid not null references public.profiles (id) on delete cascade,
  day date not null,
  value numeric(7, 1) not null default 0 check (value >= 0),
  updated_at timestamptz not null default now(),
  primary key (goal_id, day)
);
create index goal_checkins_patient_idx on public.goal_checkins (patient_id, day);

-- ---------------------------------------------------------------------------
-- Diário alimentar
-- ---------------------------------------------------------------------------
create table public.diary_entries (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  eaten_at timestamptz not null default now(),
  meal_type text not null check (meal_type in (
    'cafe_da_manha', 'lanche_da_manha', 'almoco', 'lanche_da_tarde', 'jantar', 'ceia', 'outro'
  )),
  description text not null default '',
  photo_path text,
  hunger_before smallint check (hunger_before between 1 and 5),
  satiety_after smallint check (satiety_after between 1 and 5),
  mood text,
  followed_plan boolean,
  created_at timestamptz not null default now()
);
create index diary_entries_patient_idx on public.diary_entries (patient_id, eaten_at desc);

create table public.diary_comments (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references public.diary_entries (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  body text not null check (length(trim(body)) > 0),
  created_at timestamptz not null default now()
);
create index diary_comments_entry_idx on public.diary_comments (entry_id, created_at);

-- ---------------------------------------------------------------------------
-- Mensagens (uma conversa por par paciente/profissional)
-- ---------------------------------------------------------------------------
create table public.messages (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  professional_id uuid not null references public.professionals (user_id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  body text not null default '',
  attachment_path text,
  attachment_name text,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id in (patient_id, professional_id)),
  check (length(trim(body)) > 0 or attachment_path is not null)
);
create index messages_pair_idx on public.messages (patient_id, professional_id, created_at);

-- ---------------------------------------------------------------------------
-- Documentos e exames (arquivos no bucket patient-files)
-- ---------------------------------------------------------------------------
create table public.patient_documents (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  uploaded_by uuid not null references public.profiles (id) on delete cascade,
  kind public.document_kind not null default 'exame',
  title text not null,
  file_path text not null,
  mime_type text,
  size_bytes integer,
  document_date date,
  notes text,
  created_at timestamptz not null default now()
);
create index patient_documents_patient_idx on public.patient_documents (patient_id, created_at desc);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.anamneses enable row level security;
alter table public.clinical_notes enable row level security;
alter table public.anthropometrics enable row level security;
alter table public.foods enable row level security;
alter table public.meal_plans enable row level security;
alter table public.meal_plan_meals enable row level security;
alter table public.meal_plan_items enable row level security;
alter table public.goals enable row level security;
alter table public.goal_checkins enable row level security;
alter table public.diary_entries enable row level security;
alter table public.diary_comments enable row level security;
alter table public.messages enable row level security;
alter table public.patient_documents enable row level security;

-- Anamnese: paciente lê; profissional autor lê (sempre) e escreve (vínculo ativo).
create policy "anamneses: leitura" on public.anamneses
  for select to authenticated using (
    patient_id = auth.uid() or professional_id = auth.uid()
  );
create policy "anamneses: profissional cria" on public.anamneses
  for insert to authenticated with check (
    professional_id = auth.uid() and public.has_active_link(patient_id)
  );
create policy "anamneses: profissional edita" on public.anamneses
  for update to authenticated
  using (professional_id = auth.uid() and public.has_active_link(patient_id))
  with check (professional_id = auth.uid());

-- Notas clínicas: exclusivas do profissional autor.
create policy "clinical_notes: autor lê" on public.clinical_notes
  for select to authenticated using (professional_id = auth.uid());
create policy "clinical_notes: autor cria" on public.clinical_notes
  for insert to authenticated with check (
    professional_id = auth.uid() and public.has_active_link(patient_id)
  );
create policy "clinical_notes: autor edita" on public.clinical_notes
  for update to authenticated
  using (professional_id = auth.uid() and public.has_active_link(patient_id))
  with check (professional_id = auth.uid());
create policy "clinical_notes: autor apaga" on public.clinical_notes
  for delete to authenticated using (professional_id = auth.uid() and public.has_active_link(patient_id));

-- Antropometria.
create policy "anthropometrics: leitura" on public.anthropometrics
  for select to authenticated using (
    patient_id = auth.uid()
    or professional_id = auth.uid()
    or public.has_active_link(patient_id)
  );
create policy "anthropometrics: paciente autorregistra" on public.anthropometrics
  for insert to authenticated with check (
    patient_id = auth.uid() and professional_id is null
  );
create policy "anthropometrics: profissional registra" on public.anthropometrics
  for insert to authenticated with check (
    professional_id = auth.uid() and public.has_active_link(patient_id)
  );
create policy "anthropometrics: autor edita" on public.anthropometrics
  for update to authenticated
  using (
    (professional_id = auth.uid() and public.has_active_link(patient_id))
    or (patient_id = auth.uid() and professional_id is null)
  )
  with check (
    (professional_id = auth.uid()) or (patient_id = auth.uid() and professional_id is null)
  );
create policy "anthropometrics: autor apaga" on public.anthropometrics
  for delete to authenticated using (
    (professional_id = auth.uid() and public.has_active_link(patient_id))
    or (patient_id = auth.uid() and professional_id is null)
  );

-- Alimentos: TACO público; alimentos próprios só do dono.
create policy "foods: leitura" on public.foods
  for select to authenticated using (source = 'TACO' or owner_id = auth.uid());
create policy "foods: profissional cria próprios" on public.foods
  for insert to authenticated with check (
    source = 'custom' and owner_id = auth.uid() and public.is_verified_professional()
  );
create policy "foods: profissional edita próprios" on public.foods
  for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "foods: profissional apaga próprios" on public.foods
  for delete to authenticated using (owner_id = auth.uid());

-- Planos: paciente vê publicados; profissional autor vê tudo e edita com vínculo ativo.
create or replace function public.can_read_meal_plan(p_plan uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.meal_plans m
     where m.id = p_plan
       and (m.professional_id = auth.uid() or (m.patient_id = auth.uid() and m.status <> 'rascunho'))
  );
$$;
create or replace function public.can_edit_meal_plan(p_plan uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.meal_plans m
     where m.id = p_plan and m.professional_id = auth.uid()
       and public.has_active_link(m.patient_id)
  );
$$;

create policy "meal_plans: leitura" on public.meal_plans
  for select to authenticated using (
    professional_id = auth.uid() or (patient_id = auth.uid() and status <> 'rascunho')
  );
create policy "meal_plans: profissional cria" on public.meal_plans
  for insert to authenticated with check (
    professional_id = auth.uid() and public.has_active_link(patient_id)
  );
create policy "meal_plans: profissional edita" on public.meal_plans
  for update to authenticated
  using (professional_id = auth.uid() and public.has_active_link(patient_id))
  with check (professional_id = auth.uid());
create policy "meal_plans: profissional apaga rascunho" on public.meal_plans
  for delete to authenticated using (professional_id = auth.uid() and status = 'rascunho');

create policy "meal_plan_meals: leitura" on public.meal_plan_meals
  for select to authenticated using (public.can_read_meal_plan(plan_id));
create policy "meal_plan_meals: edição" on public.meal_plan_meals
  for all to authenticated
  using (public.can_edit_meal_plan(plan_id)) with check (public.can_edit_meal_plan(plan_id));

create or replace function public.meal_plan_of_meal(p_meal uuid)
returns uuid language sql stable security definer set search_path = public as $$
  select plan_id from public.meal_plan_meals where id = p_meal;
$$;

create policy "meal_plan_items: leitura" on public.meal_plan_items
  for select to authenticated using (public.can_read_meal_plan(public.meal_plan_of_meal(meal_id)));
create policy "meal_plan_items: edição" on public.meal_plan_items
  for all to authenticated
  using (public.can_edit_meal_plan(public.meal_plan_of_meal(meal_id)))
  with check (public.can_edit_meal_plan(public.meal_plan_of_meal(meal_id)));

-- Publicar um plano arquiva o ativo anterior do mesmo profissional.
create or replace function public.publish_meal_plan(p_plan uuid)
returns public.meal_plans
language plpgsql security definer set search_path = public as $$
declare
  m public.meal_plans;
begin
  if not public.can_edit_meal_plan(p_plan) then
    raise exception 'Plano não encontrado' using errcode = '42501';
  end if;
  select * into m from public.meal_plans where id = p_plan;
  update public.meal_plans set status = 'arquivado'
   where patient_id = m.patient_id and professional_id = m.professional_id
     and status = 'ativo' and id <> p_plan;
  update public.meal_plans
     set status = 'ativo', published_at = now(), starts_on = coalesce(starts_on, current_date)
   where id = p_plan
  returning * into m;
  return m;
end;
$$;

-- Duplicar um plano (base para uma nova versão).
create or replace function public.duplicate_meal_plan(p_plan uuid)
returns public.meal_plans
language plpgsql security definer set search_path = public as $$
declare
  src public.meal_plans;
  dst public.meal_plans;
  meal record;
  new_meal uuid;
  item_map jsonb := '{}'::jsonb;
  it record;
  new_item uuid;
begin
  if not public.can_edit_meal_plan(p_plan) then
    raise exception 'Plano não encontrado' using errcode = '42501';
  end if;
  select * into src from public.meal_plans where id = p_plan;
  insert into public.meal_plans (
    patient_id, professional_id, title, status, target_kcal, target_protein_g,
    target_carbs_g, target_fat_g, guidelines
  ) values (
    src.patient_id, src.professional_id, src.title || ' (cópia)', 'rascunho', src.target_kcal,
    src.target_protein_g, src.target_carbs_g, src.target_fat_g, src.guidelines
  ) returning * into dst;

  for meal in select * from public.meal_plan_meals where plan_id = p_plan order by position loop
    insert into public.meal_plan_meals (plan_id, name, time_of_day, position, notes)
    values (dst.id, meal.name, meal.time_of_day, meal.position, meal.notes)
    returning id into new_meal;
    -- Itens principais primeiro, depois substituições apontando para os novos ids.
    for it in select * from public.meal_plan_items
               where meal_id = meal.id order by (substitute_of is not null), position loop
      insert into public.meal_plan_items (
        meal_id, substitute_of, food_id, food_name, quantity_g, household_measure,
        kcal, protein_g, carbs_g, fat_g, position, notes
      ) values (
        new_meal, (item_map ->> it.substitute_of::text)::uuid, it.food_id, it.food_name,
        it.quantity_g, it.household_measure, it.kcal, it.protein_g, it.carbs_g, it.fat_g,
        it.position, it.notes
      ) returning id into new_item;
      item_map := item_map || jsonb_build_object(it.id::text, new_item);
    end loop;
  end loop;
  return dst;
end;
$$;

-- Metas: profissional cria para o paciente; paciente também pode criar as próprias.
create policy "goals: leitura" on public.goals
  for select to authenticated using (
    patient_id = auth.uid() or professional_id = auth.uid() or public.has_active_link(patient_id)
  );
create policy "goals: criação" on public.goals
  for insert to authenticated with check (
    (patient_id = auth.uid() and professional_id is null)
    or (professional_id = auth.uid() and public.has_active_link(patient_id))
  );
create policy "goals: edição" on public.goals
  for update to authenticated
  using (
    (patient_id = auth.uid() and professional_id is null)
    or (professional_id = auth.uid() and public.has_active_link(patient_id))
  )
  with check (patient_id = auth.uid() or professional_id = auth.uid());
create policy "goals: remoção" on public.goals
  for delete to authenticated using (
    (patient_id = auth.uid() and professional_id is null)
    or (professional_id = auth.uid() and public.has_active_link(patient_id))
  );

create policy "goal_checkins: leitura" on public.goal_checkins
  for select to authenticated using (patient_id = auth.uid() or public.has_active_link(patient_id));
create policy "goal_checkins: paciente registra" on public.goal_checkins
  for all to authenticated
  using (patient_id = auth.uid())
  with check (
    patient_id = auth.uid()
    and exists (select 1 from public.goals g where g.id = goal_id and g.patient_id = auth.uid())
  );

-- Diário: paciente escreve; profissionais vinculados leem e comentam.
create policy "diary_entries: leitura" on public.diary_entries
  for select to authenticated using (patient_id = auth.uid() or public.has_active_link(patient_id));
create policy "diary_entries: paciente gerencia" on public.diary_entries
  for all to authenticated using (patient_id = auth.uid()) with check (patient_id = auth.uid());

create or replace function public.diary_entry_patient(p_entry uuid)
returns uuid language sql stable security definer set search_path = public as $$
  select patient_id from public.diary_entries where id = p_entry;
$$;

create policy "diary_comments: leitura" on public.diary_comments
  for select to authenticated using (
    public.diary_entry_patient(entry_id) = auth.uid()
    or public.has_active_link(public.diary_entry_patient(entry_id))
  );
create policy "diary_comments: participantes comentam" on public.diary_comments
  for insert to authenticated with check (
    author_id = auth.uid() and (
      public.diary_entry_patient(entry_id) = auth.uid()
      or public.has_active_link(public.diary_entry_patient(entry_id))
    )
  );
create policy "diary_comments: autor apaga" on public.diary_comments
  for delete to authenticated using (author_id = auth.uid());

-- Mensagens: só com vínculo ativo para enviar; histórico continua legível.
create policy "messages: participantes leem" on public.messages
  for select to authenticated using (patient_id = auth.uid() or professional_id = auth.uid());
create policy "messages: participantes enviam" on public.messages
  for insert to authenticated with check (
    sender_id = auth.uid()
    and (patient_id = auth.uid() or professional_id = auth.uid())
    and public.has_active_link(patient_id, professional_id)
  );
create policy "messages: destinatário marca como lida" on public.messages
  for update to authenticated
  using ((patient_id = auth.uid() or professional_id = auth.uid()) and sender_id <> auth.uid())
  with check ((patient_id = auth.uid() or professional_id = auth.uid()) and sender_id <> auth.uid());
revoke update on public.messages from authenticated, anon;
grant update (read_at) on public.messages to authenticated;

-- Documentos: paciente gerencia os seus; profissional vinculado lê e envia.
create policy "patient_documents: leitura" on public.patient_documents
  for select to authenticated using (patient_id = auth.uid() or public.has_active_link(patient_id));
create policy "patient_documents: envio" on public.patient_documents
  for insert to authenticated with check (
    uploaded_by = auth.uid() and (patient_id = auth.uid() or public.has_active_link(patient_id))
  );
create policy "patient_documents: remoção" on public.patient_documents
  for delete to authenticated using (uploaded_by = auth.uid() or patient_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Storage
--   avatars/{user_id}/...                 público
--   verification-docs/{user_id}/...       dono + admins
--   patient-files/{patient_id}/...        paciente + profissionais com vínculo ativo
--   diary-photos/{patient_id}/...         paciente + profissionais com vínculo ativo
--   chat-attachments/{patient_id}/{professional_id}/...  participantes
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
  ('avatars', 'avatars', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('verification-docs', 'verification-docs', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']),
  ('patient-files', 'patient-files', false, 20971520, array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']),
  ('diary-photos', 'diary-photos', false, 10485760, array['image/jpeg', 'image/png', 'image/webp']),
  ('chat-attachments', 'chat-attachments', false, 20971520, array['image/jpeg', 'image/png', 'image/webp', 'application/pdf'])
on conflict (id) do nothing;

create or replace function public.storage_owner(p_name text)
returns uuid language sql immutable as $$
  select case
    when (storage.foldername(p_name))[1] ~ '^[0-9a-f-]{36}$' then (storage.foldername(p_name))[1]::uuid
  end;
$$;

create policy "avatars: leitura pública" on storage.objects
  for select to anon, authenticated using (bucket_id = 'avatars');
create policy "avatars: dono envia" on storage.objects
  for insert to authenticated with check (bucket_id = 'avatars' and public.storage_owner(name) = auth.uid());
create policy "avatars: dono atualiza" on storage.objects
  for update to authenticated using (bucket_id = 'avatars' and public.storage_owner(name) = auth.uid());
create policy "avatars: dono apaga" on storage.objects
  for delete to authenticated using (bucket_id = 'avatars' and public.storage_owner(name) = auth.uid());

create policy "verification-docs: dono ou admin lê" on storage.objects
  for select to authenticated using (
    bucket_id = 'verification-docs'
    and (public.storage_owner(name) = auth.uid() or public.is_platform_admin())
  );
create policy "verification-docs: dono envia" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'verification-docs' and public.storage_owner(name) = auth.uid()
  );

create policy "patient-files: leitura" on storage.objects
  for select to authenticated using (
    bucket_id in ('patient-files', 'diary-photos')
    and (public.storage_owner(name) = auth.uid() or public.has_active_link(public.storage_owner(name)))
  );
create policy "patient-files: envio" on storage.objects
  for insert to authenticated with check (
    (bucket_id = 'patient-files'
      and (public.storage_owner(name) = auth.uid() or public.has_active_link(public.storage_owner(name))))
    or (bucket_id = 'diary-photos' and public.storage_owner(name) = auth.uid())
  );
create policy "patient-files: remoção" on storage.objects
  for delete to authenticated using (
    bucket_id in ('patient-files', 'diary-photos')
    and public.storage_owner(name) = auth.uid()
  );

create policy "chat-attachments: participantes leem" on storage.objects
  for select to authenticated using (
    bucket_id = 'chat-attachments'
    and auth.uid()::text in ((storage.foldername(name))[1], (storage.foldername(name))[2])
  );
create policy "chat-attachments: participantes enviam" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'chat-attachments'
    and auth.uid()::text in ((storage.foldername(name))[1], (storage.foldername(name))[2])
    and public.has_active_link(
      public.storage_owner(name),
      case when (storage.foldername(name))[2] ~ '^[0-9a-f-]{36}$'
        then (storage.foldername(name))[2]::uuid end
    )
  );

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------
alter publication supabase_realtime add table
  public.messages, public.appointments, public.diary_comments, public.care_links, public.payments;

-- ---------------------------------------------------------------------------
-- Permissões de execução
-- ---------------------------------------------------------------------------
revoke execute on function public.publish_meal_plan(uuid) from public, anon;
revoke execute on function public.duplicate_meal_plan(uuid) from public, anon;
